# Default values for 9c-main cluster.
# This is a YAML-formatted file.

clusterName: "9c-main-v2"
logLevel: "debug"

global:
  image:
    repository: planetariumhq/ninechronicles-headless
    tag: "41"

  appProtocolVersion: "200071/AB2da648b9154F2cCcAFBD85e0Bc3d51f97330Fc/MEUCIQCjmCK+qUHtgiVfmFIO+uBw.mI4Kpj9T20U4xdIK8I+MgIgSZPL7qAAplhILfRgXwUSDjjfQgQ7A8jgGNqzwDe+h3I=/ZHU5OnRpbWVzdGFtcHUxMDoyMDIzLTA5LTAxZQ=="
  genesisBlockPath: "https://release.nine-chronicles.com/genesis-block-9c-main"
  trustedAppProtocolVersionSigner: "030ffa9bd579ee1503ce008394f687c182279da913bfaec12baca34e79698a7cd1"

  peerStrings:
  - "027bd36895d68681290e570692ad3736750ceaab37be402442ffb203967f98f7b6,9c-main-tcp-seed-1.planetarium.dev,31234"
  - "02f164e3139e53eef2c17e52d99d343b8cbdb09eeed88af46c352b1c8be6329d71,9c-main-tcp-seed-2.planetarium.dev,31234"
  - "0247e289aa332260b99dfd50e578f779df9e6702d67e50848bb68f3e0737d9b9a5,9c-main-tcp-seed-3.planetarium.dev,31234"

  iceServers:
  - "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us.planetarium.dev:3478"
  - "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us2.planetarium.dev:3478"
  - "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us3.planetarium.dev:3478"
  - "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us4.planetarium.dev:3478"
  - "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us5.planetarium.dev:3478"

  networkType: Main
  consensusType: pbft

  resetSnapshot: false
  rollbackSnapshot: false
  useExternalSecret: true

snapshot:
  slackChannel: "9c-mainnet"
  image: "planetariumhq/ninechronicles-snapshot:git-c3669931b652f49b8b38e111c0f2c51619e436d4"

# if you want to delete PVC with the volume provisioned together, set this value "Delete"
volumeReclaimPolicy: "Retain"

seed:
  count: 3
  useTurnServer: false
  image:
    tag: "git-22bed8ef41ab09258e6404462ec8e07cd038d089"

  hosts:
  - "9c-main-tcp-seed-1.planetarium.dev"
  - "9c-main-tcp-seed-2.planetarium.dev"
  - "9c-main-tcp-seed-3.planetarium.dev"

  # dotnet args
  workerCount: 1000

  nodeSelector:
    node.kubernetes.io/instance-type: m5d.xlarge

validator:
  count: 4

  consensusSeedStrings:
  - "027bd36895d68681290e570692ad3736750ceaab37be402442ffb203967f98f7b6,9c-main-tcp-seed-1.planetarium.dev,31235"
  - "02f164e3139e53eef2c17e52d99d343b8cbdb09eeed88af46c352b1c8be6329d71,9c-main-tcp-seed-2.planetarium.dev,31235"
  - "0247e289aa332260b99dfd50e578f779df9e6702d67e50848bb68f3e0737d9b9a5,9c-main-tcp-seed-3.planetarium.dev,31235"

  hosts:
  - "9c-main-validator-5.nine-chronicles.com"
  - "9c-main-validator-6.nine-chronicles.com"
  - "9c-main-validator-7.nine-chronicles.com"
  - "9c-main-validator-8.nine-chronicles.com"

  nodeSelector:
    eks.amazonaws.com/nodegroup: 9c-internal-r6g_l_2c

remoteHeadless:
  count: 3

  useTurnServer: false

  hosts:
  - "9c-main-rpc-1.nine-chronicles.com"
  - "9c-main-rpc-2.nine-chronicles.com"
  - "9c-main-rpc-3.nine-chronicles.com"
  - "9c-main-rpc-4.nine-chronicles.com"
  - "9c-main-rpc-5.nine-chronicles.com"
  - "9c-main-rpc-6.nine-chronicles.com"
  - "9c-main-rpc-7.nine-chronicles.com"
  - "9c-main-rpc-8.nine-chronicles.com"
  - "9c-main-rpc-9.nine-chronicles.com"
  - "9c-main-rpc-10.nine-chronicles.com"

  nodeSelector:
    eks.amazonaws.com/nodegroup: 9c-internal-r6g_l_2c

  loggingEnabled: true

dataProvider:
  enabled: true
  render: true

  image:
    repository: planetariumhq/ninechronicles-dataprovider
    pullPolicy: Always
    tag: 'git-e54da4e7f84f0d7969b5050609adb71d5be139de'

  nodeSelector:
    node.kubernetes.io/instance-type: m5d.xlarge

explorer:
  enabled: true
  image:
    repository: planetariumhq/ninechronicles-headless
    pullPolicy: Always

  loggingEnabled: true

  nodeSelector:
    node.kubernetes.io/instance-type: m5d.xlarge

marketService:
  enabled: true
  image:
    tag: "git-68e6bc82786506b6c89e71f78bafc8d9bed3f23c"

  nodeSelector:
    node.kubernetes.io/instance-type: m5d.large

fullState:
  loggingEnabled: true

  useTurnServer: true

  host: "9c-main-full-state.nine-chronicles.com"

  nodeSelector:
    beta.kubernetes.io/os: linux

worldBoss:
  enabled: true

  image:
    tag: "git-05ffdb0f2af019486b3213431031bca5e86a4a3d"

bridge:
  enabled: true
  bridgeObserverImage:
    tag: "git-da9637c9ee56051a252f11ff639ed2f0d674afc6"
  bridgeStatusBotImage:
    tag: "20210913-01"

testHeadless1:
  enabled: true
  image:
    repository: planetariumhq/ninechronicles-headless
    pullPolicy: Always
    tag: "41"

  loggingEnabled: true

  host: "9c-main-test-1.nine-chronicles.com"

  nodeSelector:
    beta.kubernetes.io/os: linux

testHeadless2:
  enabled: true
  image:
    repository: planetariumhq/ninechronicles-headless
    pullPolicy: Always
    tag: "41"

  loggingEnabled: true

  host: "9c-main-test-2.nine-chronicles.com"

  nodeSelector:
    beta.kubernetes.io/os: linux

emptyChronicle:
  enabled: true

  image:
    tag: "git-2a76d3c2352243d8e1aa6315a91f729305e00f63"

remoteActionEvaluatorHeadless:
  enabled: true
  image:
    tag: "41"

  loggingEnabled: true

  useTurnServer: true

  host: "9c-main-remote-aev-test.nine-chronicles.com"

  nodeSelector:
    beta.kubernetes.io/os: linux
