{{ if and .Values.backoffice.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ninechronicles-backoffice
  namespace: {{ $.Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app: ninechronicles-backoffice
  type: LoadBalancer

---

{{ end }}
