{{- if $.Values.seasonpass.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: seasonpass-beat
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: seasonpass-beat
  namespace: {{ $.Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seasonpass-beat
  template:
    metadata:
      labels:
        app: seasonpass-beat
    spec:
      containers:
        - name: seasonpass-beat
          args:
            - celery -A app.celery_app beat --loglevel=info
          command:
            - /bin/sh
            - -c
          env:
            - name: WORKER_KMS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: kms-key-id
                  name: seasonpass-env
            - name: WORKER_REGION_NAME
              valueFrom:
                secretKeyRef:
                  key: region
                  name: seasonpass-env
            - name: WORKER_GQL_URL_MAP
              valueFrom:
                secretKeyRef:
                  key: gql-url-dict
                  name: seasonpass-env
            - name: WORKER_PG_DSN
              valueFrom:
                secretKeyRef:
                  key: db-uri
                  name: seasonpass-env
            - name: WORKER_BROKER_URL
              valueFrom:
                secretKeyRef:
                  key: rmq-url
                  name: seasonpass-env
            - name: WORKER_RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  key: redis-url
                  name: seasonpass-env
            - name: WORKER_HEADLESS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: headless-jwt-token
                  name: seasonpass-env
          image: {{ $.Values.seasonpass.worker.image.repository }}:{{ $.Values.seasonpass.image.tag }}
          {{- with $.Values.seasonpass.worker.resources }}
          resources:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          name: seasonpass-beat
      {{- with $.Values.seasonpass.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      serviceAccount: {{ $.Release.Name }}-seasonpass-iam-role
      serviceAccountName: {{ $.Release.Name }}-seasonpass-iam-role
{{- end }}
