apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petpop
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: petpop
  source:
    repoURL: https://github.com/planetarium/9c-infra.git
    targetRevision: main
    path: charts/petpop
    helm:
      valueFiles:
        - /9c-internal/petpop/values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
