externalSecretKey: petpop/internal

server:
  enabled: true
  image:
    repository: planetariumhq/petpop
    tag: server-48f02a18f72749a53b37919ed042adc2d0610b43
  hostname: internal.petpop.fun

backoffice:
  enabled: true
  image:
    repository: planetariumhq/petpop
    tag: server-48f02a18f72749a53b37919ed042adc2d0610b43
  hostname: petpop-internal-backoffice.9c.gg

workers:
  image:
    repository: planetariumhq/petpop
    tag: worker-48f02a18f72749a53b37919ed042adc2d0610b43
  rankingWorker:
    enabled: true
  blockResetWorker:
    enabled: true
  walletMonitorWorker:
    enabled: false
