externalSecretKey: petpop/internal

server:
  enabled: true
  image:
    repository: planetariumhq/petpop
    tag: server-bdcbbc7076f0bfacc54d78a41f000cf4c64fa48b
  hostname: internal.petpop.fun

backoffice:
  enabled: true
  image:
    repository: planetariumhq/petpop
    tag: server-be3b3a5101eaa6408b196ebe168fe1fa333e6cd0
  hostname: petpop-internal-backoffice.9c.gg
  nodeSelector:
    node.kubernetes.io/type: general

workers:
  image:
    repository: planetariumhq/petpop
    tag: worker-bdcbbc7076f0bfacc54d78a41f000cf4c64fa48b
  rankingWorker:
    enabled: true
  blockResetWorker:
    enabled: true
