server:
  replicas: 1
  image:
    repository: ""
    tag: ""

backoffice:
  image:
    repository: ""
    tag: ""

workers:
  image:
    repository: ""
    tag: ""
  rankingWorker:
    enabled: true
    schedule: "0 * * * *"
    command: "ranking"
  blockResetWorker:
    enabled: true
    schedule: "0 0 * * *"
    command: "reset"
