# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


clusterName: "9c-odin-libplanet4-test-20240104"
logLevel: "debug"

global:
  validatorPath: "validator-5.9c-odin-libplanet4-test-20240104.svc.cluster.local"
  image:
    repository: planetariumhq/ninechronicles-headless
    tag: "git-2b337bdd4a66a85011e6c90850147583ad10f949"

  appProtocolVersion: "1/fe4829C1650d3d5FC552516576731DBE74A5f3B1/MEQCID.oqBAHrJRhQ0myPP6eAMjnoPKz0mMn+btIdHdQ94QxAiAdV2L0l8GfQ0nat7g.6xClCWW9ue2rmarV5hBESUcwbQ=="
  genesisBlockPath: "https://release.nine-chronicles.com/genesis-block-9c-main"
  trustedAppProtocolVersionSigner: "02dac8e104ec5dec045dddb9939d83722cc0e1df523795bface7ed10ae56187638"
  headlessAppsettingsPath: "appsettings.json"

  peerStrings:
  - "033369e95dbfd970dd9a7b4df31dcf5004d7cfd63289d26cc42bbdd01e25675b6f,tcp-seed-1,31234"

  resetSnapshot: false
  rollbackSnapshot: false

snapshot:
  downloadSnapshot: true
  slackChannel: "9c-internal"
  image: "planetariumhq/ninechronicles-snapshot:git-a484e5089d57a961aa97d6e75c38980323b587e6"
  partition:
    enabled: true
    suspend: true
  path: 9c-dev-v2
  nodeSelector:
    eks.amazonaws.com/nodegroup: general-m7g_2xl_2c

externalSecret:
  enabled: true
  prefix: 9c-dev-v2
  pkPrefixOverride: 9c-internal-v2

seed:
  count: 1
  useTurnServer: false
  image:
    repository: planetariumhq/libplanet-seed
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "git-22bed8ef41ab09258e6404462ec8e07cd038d089"

  hosts:
  - "tcp-seed-1.9c-odin-libplanet4-test-20240104.svc.cluster.local"

  loggingEnabled: true

  # dotnet args
  workerCount: 1000

  nodeSelector:
    node.kubernetes.io/instance-type: m5d.large

remoteHeadless:
  count: 1
  image:
    pullPolicy: Always

  loggingEnabled: true

  useTurnServer: false

  hosts:
  - "remote-headless-1.9c-odin-libplanet4-test-20240104.svc.cluster.local"

  extraArgs:
  - --tx-quota-per-signer=1

  nodeSelector:
    eks.amazonaws.com/nodegroup: general-m7g_2xl_2c


validator:
  count: 4
  image:
    pullPolicy: Always

  loggingEnabled: true

  consensusSeedStrings:
  - "033369e95dbfd970dd9a7b4df31dcf5004d7cfd63289d26cc42bbdd01e25675b6f,tcp-seed-1,31235"

  hosts:
  - "validator-5.9c-odin-libplanet4-test-20240104.svc.cluster.local"
  - "validator-6.9c-odin-libplanet4-test-20240104.svc.cluster.local"
  - "validator-7.9c-odin-libplanet4-test-20240104.svc.cluster.local"
  - "validator-8.9c-odin-libplanet4-test-20240104.svc.cluster.local"

  extraArgs:
  - --tx-quota-per-signer=1
  - --consensus-target-block-interval=6500

  nodeSelector:
    eks.amazonaws.com/nodegroup: general-m7g_2xl_2c

dataProvider:
  enabled: true
  migrateDatabase: true

  storage:
    data: 1000Gi
    log: 4Gi

  image:
    tag: "git-3da9d207ef8237e48eeb953ea53bb5308a873aad"

  db:
    local: true
    storage: 1000Gi
    database: ''
    connectionString: ''
    host: ''
    port: 3306
    user: user
    password: ''

  nodeSelector:
    eks.amazonaws.com/nodegroup: general-m7g_xl_2c

  resources:
    requests:
      cpu: 1
      memory: 4Gi

worldBoss:
  enabled: true

  ports:
    targetPort: 5000

  db:
    local: true
    size: 5Gi

  worldBossEnv:
    databaseUrl: ""
    redisHost: ""
    redisPort: ""
    kmsKeyId: ""
    slackToken: ""
    celeryBrokerUrl: ""
    celeryResultBackend: ""
    slackSigningSecret: ""

  nodeSelector:
    eks.amazonaws.com/nodegroup: general-m5d_xl_2c

marketService:
  enabled: true
  image:
    repository: planetariumhq/market-service
    pullPolicy: Always
    tag: git-850e0ac4135a9ee3ef75c1820c00289b0996f050

  db:
    local: true
    size: 1Gi

  nodeSelector:
    node.kubernetes.io/instance-type: m5d.large

  env:
  - name: DOTNET_gcServer
    value: "1"
  - name: RpcConfig__Host
    value: k8s-9codinli-remotehe-55686c889c-fbbfdb2f7f6d58ec.elb.us-east-2.amazonaws.com
  - name: RpcConfig__Port
    value: "31238"
  - name: WorkerConfig__SyncShop
    value: "true"
  - name: WorkerConfig__SyncProduct
    value: "true"

guildService:
  enabled: false
  db:
    local: false

patrolRewardService:
  enabled: true

  nodeSelector:
    eks.amazonaws.com/nodegroup: general-m5d_xl_2c

  db:
    local: true
