{{ range $idx := until (int .Values.seed.count) }}
{{ $index := add $idx 1 }}
apiVersion: v1
kind: Service
metadata:
  name: tcp-seed-{{ $index }}
  namespace: {{ $.Chart.Name }}
spec:
  ports:
  - port: 31234
    targetPort: 31234
  selector:
    app: tcp-seed-{{ $index }}
  type: LoadBalancer
---
{{ end }}

{{ range $idx := until (int .Values.miner.count) }}
{{ $index := add $idx 1 }}
apiVersion: v1
kind: Service
metadata:
  name: miner-{{ $index }}
  namespace: {{ $.Chart.Name }}
spec:
  ports:
  - port: 31234
    targetPort: 31234
    name: headless
  - port: 80
    targetPort: 80
    name: gql
  selector:
    app: miner-{{ $index }}
  type: LoadBalancer

---
{{ end }}

{{ range $idx := until (int .Values.remoteHeadless.count) }}
{{ $index := add $idx 1 }}

apiVersion: v1
kind: Service
metadata:
  name: remote-headless-{{ $index }}
  namespace: {{ $.Chart.Name }}
spec:
  ports:
  - name: graphql
    port: 80
    targetPort: 80
  - name: rpc
    port: 31238
    targetPort: 31238
  - name: headless
    port: 31234
    targetPort: 31234
  selector:
    app: remote-headless-{{ $index }}
  type: LoadBalancer

---
{{ end }}
