apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-probe-script
  namespace: {{ $.Chart.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Chart.Name }}
data:
  liveness_probe.sh: |- {{ .Files.Get "scripts/common/liveness_probe.sh" | nindent 4 }}
  liveness_probe_miner.sh: |- {{ .Files.Get "scripts/common/liveness_probe_miner.sh" | nindent 4 }}
  readiness_probe.sh: |- {{ .Files.Get "scripts/common/readiness_probe.sh" | nindent 4 }}
