---
apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings
  namespace: 9c-network
  labels:
    app.kubernetes.io/instance: {{ $.Chart.Name }}
data:
  appsettings.json: |- {{ tpl (.Files.Get "scripts/common/appsettings.json") . | nindent 4 }}
