apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-snapshot-script-full
  namespace: {{ $.Chart.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Chart.Name }}
data:
  preload_headless.sh: |- {{ .Files.Get "scripts/snapshots/full/preload_headless.sh" | nindent 4 }}
  upload_snapshot.sh: |- {{ .Files.Get "scripts/snapshots/full/upload_snapshot.sh" | nindent 4 }}
