apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: main-full-state
    app.kubernetes.io/instance: {{ $.Chart.Name }}
  name: main-full-state
  namespace: {{ $.Chart.Name }}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: main-full-state
  serviceName: main-full-state
  template:
    metadata:
      labels:
        app: main-full-state
      name: main-full-state
    spec:
      containers:
      - args:
        - NineChronicles.Headless.Executable.dll
        - run
        - --app-protocol-version={{ $.Values.appProtocolVersion }}
        - --trusted-app-protocol-version-signer={{ $.Values.trustedAppProtocolVersionSigner }}
        - --genesis-block-path={{ $.Values.genesisBlockPath }}
        - --port={{ $.Values.fullState.ports.headless }}
        - --no-miner
        - --store-type=rocksdb
        - --store-path=/data/full-state
        {{- if $.Values.fullState.useTurnServer }}
        {{- range $.Values.iceServers }}
        - --ice-server={{ . }}
        {{- end }}
        {{- range $.Values.peerStrings }}
        - --peer={{ . }}
        {{- end }}
        - --graphql-server
        - --graphql-host=0.0.0.0
        - --graphql-port={{ $.Values.fullState.ports.graphql }}
        - --tx-life-time=10
        - --no-cors
        - --chain-tip-stale-behavior-type=reboot
        - --network-type={{ $.Values.networkType }}
        {{- with $.Values.fullState.extraArgs }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        command:
        - dotnet
        image: {{ $.Values.fullState.image.repository }}:{{ $.Values.fullState.image.tag }}
        imagePullPolicy: Always
        name: main-full-state
        ports:
        - containerPort: {{ $.Values.fullState.ports.graphql }}
          name: graphql
          protocol: TCP
        - containerPort: {{ $.Values.fullState.ports.headless }}
          name: headless
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /bin/liveness_probe.sh
          failureThreshold: 3
          initialDelaySeconds: 1800
          periodSeconds: 30
          timeoutSeconds: 30
        resources:
          {{- toYaml $.Values.fullState.resources | nindent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: main-full-state-data
        - mountPath: /bin/liveness_probe.sh
          name: probe-script
          readOnly: true
          subPath: liveness_probe.sh
        - mountPath: /bin/readiness_probe.sh
          name: probe-script
          readOnly: true
          subPath: readiness_probe.sh
        {{- if $.Values.fullState.loggingEnabled }}
        - mountPath: /app/logs
          name: json-log
        {{- end }}
        env:
        {{- if $.Values.fullState.loggingEnabled }}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JSON_LOG_PATH
          value: ./logs/$(POD_NAME)_$(NAMESPACE_NAME)_fullState.json
        {{- end }}
      nodeSelector:
        eks.amazonaws.com/nodegroup: 9c-main-r7g_xl_2c
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 448
          name: {{ $.Chart.Name }}-probe-script
        name: probe-script
      {{- if $.Values.fullState.loggingEnabled }}
      - hostPath:
          path: /var/log/headless
          type: DirectoryOrCreate
        name: json-log
        {{- end }}
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: main-full-state-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ $.Values.fullState.storage.data }}
      storageClassName: {{ $.Chart.Name }}-gp3
      volumeMode: Filesystem
---
{{ end }}
