apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Chart.Name }}-gp3-iops
  labels:
    app.kubernetes.io/instance: {{ $.Chart.Name }}
parameters:
  fsType: ext4
  iops: "6000"
  throughput: "250"
  type: gp3
provisioner: ebs.csi.aws.com
reclaimPolicy: {{ .Values.volumeReclaimPolicy }}
allowVolumeExpansion: true
