{{ if .Values.useExternalSecret }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: aws-keys
  namespace: {{ $.Chart.Name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ $.Chart.Name }}-secretsmanager
    kind: SecretStore
  target:
    name: aws-keys
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.clusterName }}/aws-keys
{{ else }}
apiVersion: v1
kind: Secret
metadata:
  name: aws-keys
  namespace: {{ $.Chart.Name }}
stringData:
  cf_distribution_id: {{ .Values.snapshot.cfDistributionId }}
  aws_access_key_id: {{ .Values.snapshot.awsAccessKeyId }}
  aws_secret_access_key: {{ .Values.snapshot.awsSecretAccessKey }}
type: Opaque
{{ end }}
