{{ range $idx := until (int .Values.seed.count) }}
{{ $index := add $idx 1 }}
apiVersion: v1
kind: Service
metadata:
  name: tcp-seed-{{ $index }}
  namespace: {{ $.Chart.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:319679068466:certificate/2481ac9e-2037-4331-9234-4b3f86d50ad3
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ports:
  - port: {{ $.Values.seed.ports.node }}
    targetPort: {{ $.Values.seed.ports.node }}
    name: node
  selector:
    app: tcp-seed-{{ $index }}
  type: LoadBalancer
---
{{ end }}

apiVersion: v1
kind: Service
metadata:
  name: main-miner-1
  namespace: {{ $.Chart.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:319679068466:certificate/2481ac9e-2037-4331-9234-4b3f86d50ad3
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ports:
  - port: {{ $.Values.miner.ports.headless }}
    targetPort: {{ $.Values.miner.ports.headless }}
    name: headless
  - port: {{ $.Values.miner.ports.graphql }}
    targetPort: {{ $.Values.miner.ports.graphql }}
    name: gql
  - port: 443
    targetPort: {{ $.Values.miner.ports.graphql }}
    name: https
  selector:
    app: main-miner-1
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: main-miner-2
  namespace: {{ $.Chart.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:319679068466:certificate/2481ac9e-2037-4331-9234-4b3f86d50ad3
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ports:
  - port: {{ $.Values.miner.ports.headless }}
    targetPort: {{ $.Values.miner.ports.headless }}
    name: headless
  - port: {{ $.Values.miner.ports.graphql }}
    targetPort: {{ $.Values.miner.ports.graphql }}
    name: gql
  - port: 443
    targetPort: {{ $.Values.miner.ports.graphql }}
    name: https
  selector:
    app: main-miner-2
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: main-miner-3
  namespace: {{ $.Chart.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:319679068466:certificate/2481ac9e-2037-4331-9234-4b3f86d50ad3
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ports:
  - port: {{ $.Values.miner.ports.headless }}
    targetPort: {{ $.Values.miner.ports.headless }}
    name: headless
  - port: {{ $.Values.miner.ports.graphql }}
    targetPort: {{ $.Values.miner.ports.graphql }}
    name: gql
  - port: 443
    targetPort: {{ $.Values.miner.ports.graphql }}
    name: https
  selector:
    app: main-miner-3
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: main-miner-4
  namespace: {{ $.Chart.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:319679068466:certificate/2481ac9e-2037-4331-9234-4b3f86d50ad3
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ports:
  - port: {{ $.Values.miner.ports.headless }}
    targetPort: {{ $.Values.miner.ports.headless }}
    name: headless
  - port: {{ $.Values.miner.ports.graphql }}
    targetPort: {{ $.Values.miner.ports.graphql }}
    name: gql
  - port: 443
    targetPort: {{ $.Values.miner.ports.graphql }}
    name: https
  selector:
    app: main-miner-4
  type: LoadBalancer

---

{{ range $idx := until (int .Values.remoteHeadless.count) }}
{{ $index := add $idx 1 }}

apiVersion: v1
kind: Service
metadata:
  name: remote-headless-{{ $index }}
  namespace: {{ $.Chart.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:319679068466:certificate/2481ac9e-2037-4331-9234-4b3f86d50ad3
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ports:
  - name: graphql
    port: {{ $.Values.remoteHeadless.ports.graphql }}
    targetPort: {{ $.Values.remoteHeadless.ports.graphql }}
  - name: rpc
    port: {{ $.Values.remoteHeadless.ports.rpc }}
    targetPort: {{ $.Values.remoteHeadless.ports.rpc }}
  - name: headless
    port: {{ $.Values.remoteHeadless.ports.headless }}
    targetPort: {{ $.Values.remoteHeadless.ports.headless }}
  - name: https
    port: 443
    targetPort: {{ $.Values.remoteHeadless.ports.graphql }}
  selector:
    app: remote-headless-{{ $index }}
  type: LoadBalancer

---
{{ end }}

apiVersion: v1
kind: Service
metadata:
  name: data-provider-write
  namespace: {{ $.Chart.Name }}
spec:
  ports:
  - name: graphql
    port: 80
    targetPort: 80
  selector:
    app: data-provider-write
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: data-provider-read
  namespace: {{ $.Chart.Name }}
spec:
  ports:
  - name: graphql
    port: 80
    targetPort: 80
  selector:
    app: data-provider-read
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: explorer
  namespace: {{ $.Chart.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:319679068466:certificate/2481ac9e-2037-4331-9234-4b3f86d50ad3
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ports:
  - name: graphql
    port: {{ $.Values.explorer.ports.graphql }}
    targetPort: {{ $.Values.explorer.ports.graphql }}
  - name: headless
    port: {{ $.Values.explorer.ports.headless }}
    targetPort: {{ $.Values.explorer.ports.headless }}
  selector:
    app: explorer
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: main-full-state
  namespace: {{ $.Chart.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:319679068466:certificate/2481ac9e-2037-4331-9234-4b3f86d50ad3
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ports:
  - name: graphql
    port: {{ $.Values.fullState.ports.graphql }}
    targetPort: {{ $.Values.fullState.ports.graphql }}
  - name: headless
    port: {{ $.Values.fullState.ports.headless }}
    targetPort: {{ $.Values.fullState.ports.headless }}
  selector:
    app: main-full-state
  type: LoadBalancer
