apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot-volume-partition
  namespace: {{ $.Chart.Name }}
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  storageClassName: {{ $.Chart.Name }}-gp3
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot-volume-full
  namespace: {{ $.Chart.Name }}
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  storageClassName: {{ $.Chart.Name }}-gp3
  volumeMode: Filesystem
