{{ range $idx := until (int .Values.validator.count) }}
{{ $index := add $idx 1 }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: validator-{{ $index }}
    app.kubernetes.io/instance: {{ $.Chart.Name }}
  name: validator-{{ $index }}
  namespace: {{ $.Chart.Name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: validator-{{ $index }}
  serviceName: validator-{{ $index }}
  template:
    metadata:
      labels:
        app: validator-{{ $index }}
      name: validator-{{ $index }}
    spec:
      containers:
      - args:
        - NineChronicles.Headless.Executable.dll
        - run
        - --app-protocol-version={{ $.Values.appProtocolVersion }}
        - --trusted-app-protocol-version-signer={{ $.Values.trustedAppProtocolVersionSigner }}
        - --genesis-block-path={{ $.Values.genesisBlockPath }}
        {{- if eq $.Values.consensusType "pbft" }}
        - --host={{ index $.Values.validator.hosts $idx }}
        {{- else }}
        {{- range $.Values.iceServers }}
        - --ice-server={{ . }}
        {{- end }}
        {{- end }}
        - --port={{ $.Values.validator.ports.headless }}
        - --store-path=/data/validator
        - --store-type=rocksdb
        {{- range $.Values.peerStrings }}
        - --peer={{ . }}
        {{- end }}
        - --graphql-server
        - --graphql-host=0.0.0.0
        - --graphql-port={{ $.Values.validator.ports.graphql }}
        {{- if eq $.Values.consensusType "pbft" }}
        - --swarm-private-key
        - $(PRIVATE_KEY)
        - --miner-private-key
        - $(PRIVATE_KEY)
        - --consensus-private-key
        - $(PRIVATE_KEY)
        - --consensus-port={{ $.Values.validator.ports.gossip }}
        {{- range $.Values.validator.consensusSeedStrings }}
        - --consensus-seed={{ . }}
        {{- end }}
        {{- end }}
        {{- with $.Values.validator.extraArgs }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        - --network-type={{ $.Values.networkType }}
        - --tx-life-time=10
        - --tx-quota-per-signer=1
        command:
          - dotnet
        env:
          - name: PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                key: validator-private-key-{{ $index }}
                name: private-keys
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JSON_LOG_PATH
            value: ./logs/$(POD_NAME)_$(NAMESPACE_NAME)_validator-{{ $index }}.json
          {{- with $.Values.validator.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        image: {{ $.Values.validator.image.repository }}:{{ $.Values.validator.image.tag }}
        imagePullPolicy: Always
        name: validator-{{ $index }}
        ports:
        - containerPort: {{ $.Values.validator.ports.headless }}
          name: headless
          protocol: TCP
        - containerPort: {{ $.Values.validator.ports.graphql }}
          name: graphql
          protocol: TCP
        - containerPort: {{ $.Values.validator.ports.gossip }}
          name: gossip
          protocol: TCP
        resources:
          {{- toYaml $.Values.validator.resources | nindent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: validator-data-{{ $index }}
        - mountPath: /bin/liveness_probe.sh
          name: probe-script
          readOnly: true
          subPath: liveness_probe.sh
        - mountPath: /bin/readiness_probe.sh
          name: probe-script
          readOnly: true
          subPath: readiness_probe.sh
        - mountPath: /app/logs
          name: json-log
        - mountPath: /app/appsettings.configmap.json
          name: appsettings
      nodeSelector:
        node.kubernetes.io/instance-type: c7g.4xlarge
      {{- with $.Values.validator.tolerations }}
      tolerations:
        {{- toYaml $.Values.validator.tolerations | nindent 8 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      volumes:
      - configMap:
          defaultMode: 448
          name: {{ $.Chart.Name }}-probe-script
        name: probe-script
      - name: download-snapshot-script
        configMap:
          defaultMode: 0700
          name: {{ $.Chart.Name }}-download-snapshot-script
      - hostPath:
          path: /var/log/headless
          type: DirectoryOrCreate
        name: json-log
      - name: appsettings
        configMap:
          defaultMode: 0700
          name: appsettings
      imagePullSecrets:
      - name: acr-regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: validator-data-{{ $index }}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ $.Values.validator.storage.data }}
      storageClassName: {{ $.Chart.Name }}-gp3
      volumeMode: Filesystem
---
{{ end }}
