portalService:
  name: portal
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1.5Gi
  image:
    repository: planetariumhq/9c-portal-internal
    tag: latest
    pullPolicy: Always
  externalSecret:
    enabled: true
    provider: AWS
    prefix: "9c-internal-v2/portal"
  env:
    NODE_ENV: development
    BASE_URL: "https://developer-mode.nine-chronicles.com"
    NEXT_PUBLIC_STATUS_SERVER_URL: "https://9c-status-portal.s3.ap-northeast-2.amazonaws.com"
    S3_BANNER_BUCKET: "9c-portal-banner-dev"
    BANNER_CLOUD_FRONT_DOMAIN: "https://d3hdj186tjvpbo.cloudfront.net/"
    QA_ENABLED: true
    NEXT_PUBLIC_MAINNET_ENV: local
    NEXT_PUBLIC_PLANETARY_ENDPOINT: "https://planets-internal.nine-chronicles.com/planets/"
