# Default values for libplanet-seed.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


clusterName: "9c-sample"
logLevel: "debug"

global:
  image:
    repository: planetariumhq/ninechronicles-headless
    tag: "git-b58a31cb2fe2d17bd759741cabb78bdd146de601"

  appProtocolVersion: "200020/54684Ac4ee5B933e72144C4968BEa26056880d71/MEQCIFp.SfFaK3PCLyqwN28j4qptXqWnToggZOQTLAFly5I3AiBr.824.h8.VwjhVwz5zulv7pKqBLARAP6pYQGPd6js+A==/ZHU4OmxhdW5jaGVydTQyOjEvODBkYjhmNDU1MTU5ODNiYWY5YjFkYjEwMDZmOWIwMjRjNWIzMWU1NnU2OnBsYXllcnU0MjoxL2M2NjUyYTEzNmQ1ZDZkMmVhOGQyNmFmNmM0M2Y1MTg5ZmJiYzYxZGN1OTp0aW1lc3RhbXB1MTA6MjAyMy0wNS0wNGU="
  genesisBlockPath: "https://release.nine-chronicles.com/genesis-block-9c-main"
  trustedAppProtocolVersionSigner: "02529a61b9002ba8f21c858224234af971e962cac9bd7e6b365e71e125c6463478"
  
  peerStrings:
  - "033369e95dbfd970dd9a7b4df31dcf5004d7cfd63289d26cc42bbdd01e25675b6f,tcp-seed-1,31234"

  resetSnapshot: true
  
  iceServers: []
  
  networkType: Default
  consensusType: pbft
  
  useExternalSecret: true
  slackToken: ""
  slackWebHookUrl: ""

snapshot:
  slackChannel: "bot-test"
  image: "planetariumhq/ninechronicles-snapshot:git-fc194ebdc47ec4ebe14f97f5ea01ff97b0a276d6"

  # aws information for uploading snapshot
  # Do not upload values below filled
  # recommended to obtain from ExternalSecret
  cfDistributionId: ""
  aws_access_key_id: ""
  aws_secret_access_key: ""

  resources:
    requests:
      cpu: 1300m
      memory: 20Gi

  nodeSelector: {}

# if you want to delete PVC with the volume provisioned together, set this value "Delete"
volumeReclaimPolicy: "Delete"

seed:
  count: 1
  useTurnServer: false
  image:
    repository: planetariumhq/libplanet-seed
    pullPolicy: Always # Overrides the image tag whose default is the chart appVersion.
    tag: "git-22bed8ef41ab09258e6404462ec8e07cd038d089"

  hosts:
  - "9c-sample-tcp-seed-1.planetarium.dev"

  ports:
    node: 31234
    gossip: 31235
    graphql: 31237

  # dotnet args
  workerCount: 1000

  extraArgs: []
  # - --key=val

  # enter private keys if not using External Secrets
  privateKeys:
  - ""

  env: []

  resources:
    requests:
      cpu: 1

  nodeSelector:
    eks.amazonaws.com/nodegroup: 9c-sample-c5_l_2c
  tolerations: []
  affinity: {}

remoteHeadless:
  count: 1
  image:
    # follow global image
    repository: ""
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
    pullPolicy: Always

  # dotnet args

  extraArgs: []
  # - --key=val

  useTurnServer: false

  hosts:
  - "9c-sample-rpc-1.planetarium.dev"

  ports:
    headless: 31234
    graphql: 80
    rpc: 31238

  storage:
    data: 1000Gi

  resources:
    requests:
      cpu: 1
      memory: 16Gi

  nodeSelector:
    eks.amazonaws.com/nodegroup: 9c-sample-r6g_xl_2c
    
  tolerations: []
  affinity: {}

validator:
  count: 4
  image:
    repository: ""
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
    pullPolicy: Always

  consensusSeedStrings:
  - "033369e95dbfd970dd9a7b4df31dcf5004d7cfd63289d26cc42bbdd01e25675b6f,tcp-seed-1,31234"

  hosts:
  - "9c-sample-validator-1.planetarium.dev"
  - "9c-sample-validator-2.planetarium.dev"
  - "9c-sample-validator-3.planetarium.dev"
  - "9c-sample-validator-4.planetarium.dev"

  ports:
    headless: 31234
    graphql: 80
    gossip: 6000

  # dotnet args

  extraArgs: []
  # - --key=val

  # private keys if not using External Secrets
  privateKeys:
  - ""
  - ""
  - ""
  - ""

  storage:
    data: 1000Gi

  env: []

  resources:
    requests:
      cpu: 2
      memory: 20Gi

  nodeSelector:
    eks.amazonaws.com/nodegroup: 9c-sample-r6g_xl_2c

  tolerations: []
  affinity: {}
