clusterName: srdg

useExternalSecret: true

image:
  repository: kong/kong-gateway
  pullPolicy: Always
  tag: "3.5.0.1"

acmArn: "arn:aws:acm:ap-northeast-2:319679068466:certificate/4d151da1-8d70-426a-ba65-cabcf10686e5"

storage:
  class: gp3-extensible

nodeSelector:
  node.kubernetes.io/instance-type: m5.large
