{{ if .Values.dataProvider.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: data-provider
  name: data-provider
  namespace: {{ $.Chart.Name }}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: data-provider
  serviceName: data-provider
  template:
    metadata:
      labels:
        app: data-provider
    spec:
      initContainers:
      - args:
        - https://snapshots.nine-chronicles.com/internal
        - /data/headless
        - $(RESET_SNAPSHOT_OPTION)
        - data-provider
        - $(SLACK_TOKEN)
        command:
        - /bin/download_snapshot.sh
        image: bash:latest
        name: reset-snapshot
        volumeMounts:
        - name: script-volume
          mountPath: /bin/download_snapshot.sh
          readOnly: true
          subPath: download_snapshot.sh
        - mountPath: /data
          name: data-provider-data
        env:
        - name: RESET_SNAPSHOT_OPTION
          value: "{{ $.Values.resetSnapshot }}"
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-token
              key: slack-token
      containers:
      - args:
        - /bin/setup_internal_db.sh $(NC_MySqlConnectionString) $(RESET_SNAPSHOT_OPTION)
          && /bin/check_chain_tip.sh $(DP_HOST) $(DP_USER) $(DP_TOKEN) $(DP_PORT) $(DP_DATABASE) $(RESET_SNAPSHOT_OPTION)
          && /app/NineChronicles.DataProvider.Executable
        command:
        - /bin/sh
        - -c
        command:
        - dotnet
        env:
        - name: NC_StorePath
          value: /data/data-provider
        - name: NC_AppProtocolVersionToken
          value: {{ $.Values.appProtocolVersion }}
        - name: NC_Confirmations
          value: '0'
        {{ range $idx, $peer := $.Values.peerStrings }}
        - name: NC_PeerString_{{ $idx }}
          value: {{ $peer}}
        {{ end }}
        - name: NC_Preload
          value: 'true'
        - name: NC_NoMiner
          value: 'true'
        - name: NC_Render
          value: 'false'
        - name: NC_TrustedAppProtocolVersionSigners__0
          value: {{ $.Values.trustedAppProtocolVersionSigner }}
        - name: NC_GenesisBlockPath
          value: {{ $.Values.genesisBlockPath }}
        - name: NC_MySqlConnectionString
          valueFrom:
            secretKeyRef:
              key: connectionString
              name: data-provider
        - name: DP_HOST
          valueFrom:
            secretKeyRef:
              key: host
              name: data-provider
        - name: DP_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: data-provider
        - name: DP_TOKEN
          valueFrom:
            secretKeyRef:
              key: password
              name: data-provider
        - name: DP_PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: data-provider
        - name: DP_DATABASE
          valueFrom:
            secretKeyRef:
              key: database
              name: data-provider
        image: {{ $.Values.dataProvider.image.repository }}:{{ $.Values.dataProvider.image.tag }}
        imagePullPolicy: {{ $.Values.dataProvider.image.pullPolicy }}
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "set -e\nlast_block=\"$(\n  curl \\\n    -H 'Content-Type: application/json'\
              \ \\\n    --data '{\"query\":\"query{chainQuery{blockQuery{blocks(desc:true,limit:1){timestamp}}}}\"\
              }' \\\n    http://localhost:80/graphql_headless \\\n  | jq -r '.data.chainQuery.blockQuery.blocks[0].timestamp'\n\
              )\"\nlast_timestamp=\"$(date +%s -u --date=\"$last_block\")\"\nnow=\"\
              $(date +%s -u)\"\n[[ $(( now - last_timestamp )) -lt 300 ]]\n"
          failureThreshold: 5
          initialDelaySeconds: 600
          periodSeconds: 30
          timeoutSeconds: 30
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "set -e\npreloaded=\"$(\n  curl \\\n    -H 'Content-Type: application/json'\
              \ \\\n    --data '{\"query\":\"query{nodeStatus{preloadEnded}}\"}' \\\
              \n    http://localhost:80/graphql_headless \\\n  | jq .data.nodeStatus.preloadEnded\n\
              )\"\n[[ \"$preloaded\" = \"true\" ]]\n"
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 10
        name: data-provider
        ports:
        - containerPort: 80
          name: graphql
          protocol: TCP
        resources:
          requests:
            cpu: 1300m
            memory: 7Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data-provider-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: script-volume
        configMap:
          defaultMode: 0700
          name: {{ $.Chart.Name }}-snapshot-script
      - name: data-provider-script
        configMap:
          defaultMode: 488
          name: {{ $.Chart.Name }}-data-provider-script
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      name: data-provider-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ $.Values.dataProvider.storage.data }}
      storageClassName: {{ $.Chart.Name }}-gp3
      volumeMode: Filesystem
{{ end }}
