{{ if .Values.dataProvider.db.create }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Chart.Name }}-data-provider-db
  name: {{ .Chart.Name }}-data-provider-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-data-provider-db
  serviceName: {{ .Chart.Name }}-data-provider-db
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-data-provider-db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: dp
            - name: MYSQL_ROOT_PASSWORD
              value: dp-pw
          image: mysql:8.0.30
          name: {{ .Chart.Name }}-data-provider-db
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: {{ .Chart.Name }}-data-provider-db-data
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        name: {{ .Chart.Name }}-data-provider-db-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ $.Values.dataProvider.db.storage }}
        storageClassName: {{ $.Chart.Name }}-gp3
        volumeMode: Filesystem
{{ end }}
