{{ if .Values.useExternalSecret }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
  namespace: {{ $.Chart.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Chart.Name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ $.Chart.Name }}-secretsmanager
    kind: SecretStore
  target:
    name: argocd-notifications-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.clusterName }}/argocd-notifications-secret
{{ else }}
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: {{ $.Chart.Name }}
stringData:
  slack-token: {{ .Values.slackToken }}
type: Opaque
{{ end }}
