{{ if .Values.useExternalSecret }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: data-provider
  namespace: {{ $.Chart.Name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ $.Chart.Name }}-secretsmanager
    kind: SecretStore
  target:
    name: data-provider
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.clusterName }}/data-provider
{{ else }}
apiVersion: v1
kind: Secret
metadata:
  name: data-provider
  namespace: {{ $.Chart.Name }}
stringData:
  username: {{ .Values.dataProvider.db.username }}
type: Opaque
{{ end }}
