{{ if .Values.useExternalSecret }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: slack-token
  namespace: {{ $.Chart.Name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ $.Chart.Name }}-secretsmanager
    kind: SecretStore
  target:
    name: slack-token
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.clusterName }}/slack-token
{{ else }}
apiVersion: v1
kind: Secret
metadata:
  name: slack
  namespace: {{ $.Chart.Name }}
stringData:
  slack-token: {{ .Values.slackToken }}
type: Opaque
{{ end }}
