{{ if .Values.useExternalSecret }}
apiVersion: "external-secrets.io/v1beta1"
kind: SecretStore
metadata:
  name: {{ $.Chart.Name }}-secretsmanager
  namespace: {{ $.Chart.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Chart.Name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
{{ end }}
