clusterName: 9c-main
provider: RKE2

externalSecret:
  enabled: true
  provider: AWS
  prefix: "9c-main-v2/external-services"

gateway:
  enabled: true
  services:
  - name: seasonpass-api-service
    hostname: seasonpass.9c.gg

volumeReclaimPolicy: "Retain"

seasonpass:
  enabled: true
  image:
    tag: "git-d76514a94ed0d4c6b3e9216ae8f5e657c271af00"

  api:
    enabled: true
    stage: "mainnet"
    nodeSelector:
      node.kubernetes.io/node-index: "2"
      node.kubernetes.io/provisioner: "cloudv"
      node.kubernetes.io/type: "general"

  worker:
    enabled: true
    serviceAccount:
      roleArn: "arn:aws:iam::319679068466:role/9c-main-v2-seasonpass-worker"
    flower:
      enabled: true

    nodeSelector:
      node.kubernetes.io/node-index: "2"
      node.kubernetes.io/provisioner: "cloudv"
      node.kubernetes.io/type: "general"


  tracker:
    enabled: true

    nodeSelector:
      node.kubernetes.io/node-index: "2"
      node.kubernetes.io/provisioner: "cloudv"
      node.kubernetes.io/type: "general"

    odin:
      planetId: "0x000000000000"
    heimdall:
      planetId: "0x000000000001"

    resources:
      limits:
        cpu: 0.5
        memory: 1Gi

backoffice:
  enabled: true

  image:
    pullPolicy: Always
    tag: "git-ee3e270ad72f32637cf4a9eed7e4e7e50e4b5611"
