# Default values for libplanet-seed.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


clusterName: ""
logLevel: ""
appProtocolVersion: ""
genesisBlockPath: ""
trustedAppProtocolVersionSigner: ""

peerStrings:
- "027bd36895d68681290e570692ad3736750ceaab37be402442ffb203967f98f7b6,9c-main-tcp-seed-1.planetarium.dev,31234"

iceServers:
- "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us.planetarium.dev:3478"
- "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us2.planetarium.dev:3478"
- "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us3.planetarium.dev:3478"
- "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us4.planetarium.dev:3478"
- "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us5.planetarium.dev:3478"

networkType: ""
consensusType: pbft

useExternalSecret: false
slackToken: ""
slackWebHookUrl: ""

snapshot:
  resetSnapshot: false
  slackChannel: ""
  image: "planetariumhq/ninechronicles-snapshot:git-aaa36c4a632b7779b540a188f0c95c2cce619c15"

  # aws information for uploading snapshot
  # Do not upload values below filled
  # recommended to obtain from ExternalSecret
  cfDistributionId: ""
  aws_access_key_id: ""
  aws_secret_access_key: ""

# if you want to delete PVC with the volume provisioned together, set this value "Delete"
volumeReclaimPolicy: "Delete"

validator:
  count: 4
  image:
    repository: planetariumhq/ninechronicles-headless
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  consensusSeedStrings:
  - "027bd36895d68681290e570692ad3736750ceaab37be402442ffb203967f98f7b6,9c-main-tcp-seed-1.planetarium.dev,31235"

  hosts:
  - "9c-main-validator-1.nine-chronicles.com"
  - "9c-main-validator-2.nine-chronicles.com"
  - "9c-main-validator-3.nine-chronicles.com"
  - "9c-main-validator-4.nine-chronicles.com"

  ports:
    headless: 31234
    graphql: 80
    gossip: 6000

  # dotnet args

  extraArgs: []
  # - --key=val

  # private keys if not using External Secrets
  privateKeys: []
  # - "<private key>"

  storage:
    data: 1000Gi

  env: []

  resources:
    requests:
      cpu: 2
      memory: 20Gi

  nodeSelector: {}
  tolerations: []
  affinity: {}
