apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backoffice-service
  labels:
    app: {{ .Release.Name }}
    component: backoffice
spec:
  type: {{ .Values.backofficeService.service.type }}
  ports:
    - port: {{ .Values.backofficeService.service.port }}
      targetPort: {{ .Values.backofficeService.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}
    component: backoffice
