apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-backoffice-secrets
  namespace: {{ .Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: backoffice
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Release.Name }}-backoffice-secret-store
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-backoffice-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.backofficeService.externalSecret.prefix }}/env
