apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backoffice-config
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: backoffice
data:
  {{- range $key, $value := .Values.backofficeService.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

