{{- if .Values.backofficeService.hostname }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-backoffice-httproute
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: backoffice
  namespace: {{ .Release.Name }}
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: web
    - name: traefik-gateway
      namespace: traefik
      sectionName: websecure
  hostnames:
    - {{ .Values.backofficeService.hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: backoffice-service
          port: {{ .Values.backofficeService.service.port }}
{{- end }}
