# charts/portal/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: portal
  namespace: {{ .Release.Name }}
data:
  {{- range $key, $value := .Values.portalService.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

