{{- if .Values.portalService.hostname }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-portal-httproute
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: portal
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: web
    - name: traefik-gateway
      namespace: traefik
      sectionName: websecure
  hostnames:
    - {{ .Values.portalService.hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: portal-service
          port: {{ .Values.portalService.service.port }}
{{- end }}
