apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}-secret-store
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: portal
  namespace: {{ .Release.Name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
