clusterName: 9c-main-v2

environment: "production"

useExternalSecret: true

image:
  repository: kong/kong-gateway
  pullPolicy: Always
  tag: "3.5.0.1"

acmArn: "arn:aws:acm:us-east-2:319679068466:certificate/583319f8-f43f-4563-bb2f-2eedf14d8f89"

storage:
  class: gp3-extensible

nodeSelector:
  node.kubernetes.io/instance-type: m5.large
