# Default values for libplanet-seed.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


clusterName: "9c-internal-v2"
logLevel: ""
namespace: "9c-single"

appProtocolVersion: "200071/AB2da648b9154F2cCcAFBD85e0Bc3d51f97330Fc/MEUCIQCjmCK+qUHtgiVfmFIO+uBw.mI4Kpj9T20U4xdIK8I+MgIgSZPL7qAAplhILfRgXwUSDjjfQgQ7A8jgGNqzwDe+h3I=/ZHU5OnRpbWVzdGFtcHUxMDoyMDIzLTA5LTAxZQ=="
genesisBlockPath: "http://54.91.246.32:38080/genesis-block"
trustedAppProtocolVersionSigner: "030ffa9bd579ee1503ce008394f687c182279da913bfaec12baca34e79698a7cd1"

peerStrings:
- "0204e015dc185b0eb0b6bdbca5a5ca220525749353f303a343273a4812f53dc4ae,localhost,31234"

iceServers: []

networkType: Default
consensusType: pbft

slackToken: ""
slackWebHookUrl: ""

# if you want to delete PVC with the volume provisioned together, set this value "Delete"
volumeReclaimPolicy: "Retain"

snapshot:
  enabled: false
  path: "internal"

externalSecret:
  enabled: true
  prefix: "9c-single"

count: 1
image:
  repository: planetariumhq/ninechronicles-headless
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "git-2fc735ec02d4d4e9ea4abb2000d34f0a491412de"

consensusSeedStrings:
- "0204e015dc185b0eb0b6bdbca5a5ca220525749353f303a343273a4812f53dc4ae,localhost,6000"

hosts:
- "9c-single-validator-1.nine-chronicles.com"

ports:
  headless: 31234
  graphql: 80
  gossip: 6000

# dotnet args

extraArgs: []
# - --key=val

# private keys if not using External Secrets
privateKeys: []
# - "<private key>"

storage:
  class: "9c-network-gp3"
  data: 500Gi

env: []

resources:
  requests:
    cpu: 2
    memory: 4Gi

nodeSelector: {}
tolerations: []
affinity: {}
