apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aws-application-networking-system
resources:
  - https://raw.githubusercontent.com/aws/aws-application-networking-k8s/main/files/controller-installation/deploy-v1.0.6.yaml
  - https://raw.githubusercontent.com/aws/aws-application-networking-k8s/main/files/controller-installation/gatewayclass.yaml
patchesJson6902:
  - target:
      kind: ServiceAccount
      name: gateway-api-controller
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          managed-by: "argocd"
