namespace: "9c-sample"

ports:
  targetPort: 5000

image:
  repository: planetariumhq/world-boss-service
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "git-f0ad3803c6034438715a782840a7776127ddb3ed"

nodeSelector:
  node.kubernetes.io/instance-type: m5.large

serviceAccount:
  create: true
  name: worldboss
  iamRole: arn:aws:iam::319679068466:role/9c-onboarding-eks

worldBossEnv:
  databaseUrl: ""
  redisHost: ""
  redisPort: ""
  kmsKeyId: ""
  slackToken: ""
  celeryBrokerUrl: ""
  celeryResultBackend: ""
  slackSigningSecret: ""
