clusterName: 9c-internal
provider: RKE2
RKE2:
  domain: rke2.planetarium.network
  publicIPs:
    - 49.247.14.112/32
argocd:
  domain: argocd-internal.planetarium.network
  cssUrl: https://9c-cluster-config.s3.us-east-2.amazonaws.com/9c-internal/css/argocd.css
externalSecrets:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::319679068466:role/gke-9c-internal-external-secrets
externalDns:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::319679068466:role/gke-external-dns
certManager:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::319679068466:role/gke-external-dns
  dnsNames:
    - "*.nine-chronicles.com"
    - "*.planetarium.network"
    - "*.planetarium.team"
    - "*.9c.gg"
    - "*.petpop.fun"
  issuer:
    email: devops@planetariumhq.com
traefik:
  ports:
    postgresql:
      port: 5432
      transport:
        respondingTimeouts:
          readTimeout: 0
grafana:
  hosts:
    - monitoring-internal.planetarium.network
prometheus:
  server:
    extraScrapeConfigs:
      - job_name: scrape-headlesses
        metrics_path: /metrics
        scrape_interval: 8s
        scrape_timeout: 6s
        static_configs:
