externalSecret:
  enabled: true
  prefix: "mothership-devnet"

env:
  L1_RPC: https://ethereum-holesky-rpc.publicnode.com
  L1_BEACON_RPC: https://ethereum-holesky-beacon-api.publicnode.com

storageClassName: gp3-extensible
awsLoadBalancerSslCert: arn:aws:acm:us-east-2:533267452421:certificate/6982734d-3034-4d0c-82e9-26aee4e0e6fd

genesis:
  source: https://mothership-holesky-devnet-use2.s3.us-east-2.amazonaws.com
  createSnapshot: true
  s3SnapshotPath: mothership-holesky-devnet-use2/snapshot

blockscout:
  enabled: true
  loadBalancerExternal: true
  db:
    local: false
    secretKeyRef:
      name: private-keys
      key: BLOCKSCOUT_DATABASE_URL

sequencer:
  enabled: true
  nodeIndex: "1"
  scheme: "http"
  host: "node-1"
  port:
    geth: 8545
    node: 8547

node:
  count: 1
  loadBalancerExternal: true
  hosts:
    - node-1.v8-dev.us-east-2.holesky.tests.mothership-pla.net
  opGeth:
    resources:
      requests:
        memory: 2Gi
    volume:
      storage: 200Gi
  nodeSelector:
    eks.amazonaws.com/nodegroup: mothership-use2-r7g_medium_2c_node

opBatcher:
  nodeSelector:
    eks.amazonaws.com/nodegroup: mothership-use2-r7g_medium_2c_node

opProposer:
  nodeSelector:
    eks.amazonaws.com/nodegroup: mothership-use2-r7g_medium_2c_node

bundler:
  enabled: true
  loadBalancerExternal: true

proxyd:
  enabled: true
  loadBalancerExternal: true
  nodeSelector:
    eks.amazonaws.com/nodegroup: mothership-use2-m7a_medium_2c
