{{ if .Values.global.useExternalSecret }}
apiVersion: "external-secrets.io/v1beta1"
kind: SecretStore
metadata:
  name: {{ $.Release.Name }}-secretsmanager
  namespace: {{ $.Release.Name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
{{ end }}
