{{ if .Values.useExternalSecret }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: private-keys
  namespace: {{ $.Chart.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Chart.Name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ $.Chart.Name }}-secretsmanager
    kind: SecretStore
  target:
    name: private-keys
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.clusterName }}/private-keys
{{ else }}
apiVersion: v1
kind: Secret
metadata:
  name: private-keys
  namespace: {{ $.Chart.Name }}
stringData:
  {{- range $idx, $privateKey := .Values.validator.privateKeys }}
  {{- $index := add $idx 1 }}
  validator-private-key-{{ $index }}: {{ $privateKey }}
  {{- end }}
  {{- range $idx, $privateKey := .Values.seed.privateKeys }}
  {{- $index := add $idx 1 }}
  seed-private-key-{{ $index }}: {{ $privateKey }}
  {{- end }}
type: Opaque
{{ end }}
