{{ range $idx := until (int .Values.seed.count) }}
{{ $index := add $idx 1 }}
apiVersion: v1
kind: Service
metadata:
  name: tcp-seed-{{ $index }}
  namespace: {{ $.Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  externalTrafficPolicy: Local
  ports:
  - port: {{ $.Values.seed.ports.node }}
    targetPort: {{ $.Values.seed.ports.node }}
    name: node
  - port: {{ $.Values.seed.ports.graphql }}
    targetPort: {{ $.Values.seed.ports.graphql }}
    name: graphql
  - port: {{ $.Values.seed.ports.gossip }}
    targetPort: {{ $.Values.seed.ports.gossip }}
    name: gossip
  selector:
    app: tcp-seed-{{ $index }}
  type: LoadBalancer
---
{{ end }}

{{ range $idx := until (int .Values.remoteHeadless.count) }}
{{ $index := add $idx 1 }}

apiVersion: v1
kind: Service
metadata:
  name: remote-headless-{{ $index }}
  namespace: {{ $.Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  externalTrafficPolicy: Local
  ports:
  - name: graphql
    port: {{ $.Values.remoteHeadless.ports.graphql }}
    targetPort: {{ $.Values.remoteHeadless.ports.graphql }}
  - name: rpc
    port: {{ $.Values.remoteHeadless.ports.rpc }}
    targetPort: {{ $.Values.remoteHeadless.ports.rpc }}
  - name: headless
    port: {{ $.Values.remoteHeadless.ports.headless }}
    targetPort: {{ $.Values.remoteHeadless.ports.headless }}
  - name: https
    port: 443
    targetPort: {{ $.Values.remoteHeadless.ports.graphql }}
  selector:
    app: remote-headless-{{ $index }}
  type: LoadBalancer

---
{{ end }}

{{ range $idx := until (int .Values.validator.count) }}
{{ $index := add $idx 1 }}
apiVersion: v1
kind: Service
metadata:
  name: validator-{{ $index }}
  namespace: {{ $.Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ports:
  - port: {{ $.Values.validator.ports.headless }}
    targetPort: {{ $.Values.validator.ports.headless }}
    name: headless
  - port: {{ $.Values.validator.ports.graphql }}
    targetPort: {{ $.Values.validator.ports.graphql }}
    name: gql
  - port: {{ $.Values.validator.ports.gossip }}
    targetPort: {{ $.Values.validator.ports.gossip }}
    name: gossip
  - port: 443
    targetPort: {{ $.Values.validator.ports.graphql }}
    name: https
    protocol: TCP
  selector:
    app: validator-{{ $index }}
  type: LoadBalancer

---
{{ end }}
