apiVersion: apps/v1
kind: Deployment
metadata:
  name: petpop
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: petpop
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: petpop
    spec:
      containers:
        - name: petpop
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - sh
            - '-c'
            - npx vite build && npx tsc -p tsconfig.game.json && node dist/server.js
          ports:
            - containerPort: 3407
          envFrom:
            - secretRef:
                name: petpop-env
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      restartPolicy: Always
