{{- if .Values.server.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petpop
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: petpop
  replicas: {{ .Values.server.replicas }}
  template:
    metadata:
      labels:
        app: petpop
    spec:
      containers:
        - name: petpop
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          command:
            - pnpm
            - run
            - start
          ports:
            - containerPort: 3407
          envFrom:
            - secretRef:
                name: petpop-env
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
{{- end }}
