{{- if or .Values.hostname .Values.hostnames }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: petpop
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: web
    - name: traefik-gateway
      namespace: traefik
      sectionName: websecure
  hostnames:
    {{- with (.Values.hostnames | default (list .Values.hostname)) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: petpop
          port: 80
{{- end }}
---
{{- if or .Values.backoffice.hostname .Values.backoffice.hostnames }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: petpop-backoffice
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: web
    - name: traefik-gateway
      namespace: traefik
      sectionName: websecure
  hostnames:
    {{- with (.Values.backoffice.hostnames | default (list .Values.backoffice.hostname)) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: petpop-backoffice
          port: 80
{{- end }}
