{{- if .Values.externalSecretKey }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: petpop-env
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Release.Name }}-secretsmanager
    kind: SecretStore
  target:
    name: petpop-env
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.externalSecretKey }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: petpop-secretsmanager
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
{{- end }}
