apiVersion: v1
kind: Service
metadata:
  name: petpop
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: petpop
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3407
