apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: petpop
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: petpop
  serviceName: petpop
  template:
    metadata:
      labels:
        app: petpop
    spec:
      containers:
        - name: petpop
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3407
          envFrom:
            - secretRef:
                name: petpop-env
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | indent 8 }}
      {{- end }}
      restartPolicy: Always
  updateStrategy:
    type: RollingUpdate
