namespace: 9c-network

serviceAccount:
  roleArn: arn:aws:iam::319679068466:role/volume-rotator

image:
  repository: planetariumhq/ninechronicles-volumerotator
  tag: "git-bed7f2b80e1ffd31f952411fb8d7d092daafdaa1"

nodeSelector:
  node.kubernetes.io/instance-type: r6g.large

headless:
  snapshotPath: "internal"
  nodeSelectorValue: "9c-internal-r6g_l_2c"
