namespace: 9c-network

serviceAccount:
  roleArn: arn:aws:iam::319679068466:role/volume-rotator

image:
  repository: planetariumhq/ninechronicles-volumerotator
  tag: "git-035daf270e293a122e54772bfdea9c21363a8eca"

nodeSelector:
  node.kubernetes.io/instance-type: r6g.large

headless:
  image: ""
  snapshotPath: "internal"
  nodeSelectorValue: "9c-internal-r6g_l_2c"
  replicaCount: 4
