externalSecretKey: petpop/prod

server:
  image:
    repository: planetariumhq/petpop
    tag: server-afdc14da19218bad0d9029fb9b56c331a18b5786
  hostnames:
    - petpop.fun
    - www.petpop.fun
  nodeSelector:
    node.kubernetes.io/type: general

backoffice:
  image:
    repository: planetariumhq/petpop
    tag: server-afdc14da19218bad0d9029fb9b56c331a18b5786
  hostname: petpop-backoffice.9c.gg
  nodeSelector:
    node.kubernetes.io/type: general

workers:
  image:
    repository: planetariumhq/petpop
    tag: worker-afdc14da19218bad0d9029fb9b56c331a18b5786
  nodeSelector:
    node.kubernetes.io/type: general
