externalSecretKey: petpop/prod

server:
  enabled: true
  image:
    repository: planetariumhq/petpop
    tag: server-b0b5a7d0f31847a87290265ea23f112808bd6da7
  hostnames:
    - petpop.fun
    - www.petpop.fun
  hpa:
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  nodeSelector:
    node.kubernetes.io/type: general

backoffice:
  enabled: true
  image:
    repository: planetariumhq/petpop
    tag: server-b0b5a7d0f31847a87290265ea23f112808bd6da7
  hostname: petpop-backoffice.9c.gg
  nodeSelector:
    node.kubernetes.io/type: general

workers:
  image:
    repository: planetariumhq/petpop
    tag: worker-b0b5a7d0f31847a87290265ea23f112808bd6da7
  nodeSelector:
    node.kubernetes.io/type: general
  rankingWorker:
    enabled: true
  blockResetWorker:
    enabled: true
  walletMonitorWorker:
    enabled: true
