hostnames:
  - petpop.fun
  - www.petpop.fun

externalSecretKey: petpop/prod

replicas: 1
nodeSelector:
  node.kubernetes.io/type: general

server:
  image:
    repository: planetariumhq/petpop
    tag: server-afdc14da19218bad0d9029fb9b56c331a18b5786

backoffice:
  image:
    repository: planetariumhq/petpop
    tag: server-afdc14da19218bad0d9029fb9b56c331a18b5786

workers:
  image:
    repository: planetariumhq/petpop
    tag: worker-afdc14da19218bad0d9029fb9b56c331a18b5786
