externalSecretKey: petpop/prod

server:
  enabled: true
  image:
    repository: planetariumhq/petpop
    tag: server-8411c5d217d949a5ea3a44412598762a06e75ea6
  hostnames:
    - petpop.fun
    - www.petpop.fun
  hpa:
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  nodeSelector:
    node.kubernetes.io/type: general

backoffice:
  enabled: true
  image:
    repository: planetariumhq/petpop
    tag: server-8411c5d217d949a5ea3a44412598762a06e75ea6
  hostname: petpop-backoffice.9c.gg
  nodeSelector:
    node.kubernetes.io/type: general

workers:
  image:
    repository: planetariumhq/petpop
    tag: worker-8411c5d217d949a5ea3a44412598762a06e75ea6
  nodeSelector:
    node.kubernetes.io/type: general
  rankingWorker:
    enabled: true
  blockResetWorker:
    enabled: true
