externalSecretKey: petpop/prod

server:
  enabled: true
  image:
    repository: planetariumhq/petpop
    tag: server-b1b5131d805cf8ef45a4847d827a377c6ddc79c2
  hostnames:
    - petpop.fun
    - www.petpop.fun
  hpa:
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  nodeSelector:
    node.kubernetes.io/type: general

backoffice:
  enabled: true
  image:
    repository: planetariumhq/petpop
    tag: server-b1b5131d805cf8ef45a4847d827a377c6ddc79c2
  hostname: petpop-backoffice.9c.gg
  nodeSelector:
    node.kubernetes.io/type: general

workers:
  image:
    repository: planetariumhq/petpop
    tag: worker-b1b5131d805cf8ef45a4847d827a377c6ddc79c2
  nodeSelector:
    node.kubernetes.io/type: general
  rankingWorker:
    enabled: true
  blockResetWorker:
    enabled: true
