externalSecretKey: petpop/prod

server:
  enabled: true
  image:
    repository: planetariumhq/petpop
    tag: server-5056fe94c5d9f6d0147aba40158590829d801b8a
  hostnames:
    - petpop.fun
    - www.petpop.fun
  hpa:
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  nodeSelector:
    node.kubernetes.io/type: general

backoffice:
  enabled: true
  image:
    repository: planetariumhq/petpop
    tag: server-ebf5da42baffef05e00b6ac5940d0e3cd50491e3
  hostname: petpop-backoffice.9c.gg
  nodeSelector:
    node.kubernetes.io/type: general

workers:
  image:
    repository: planetariumhq/petpop
    tag: worker-ebf5da42baffef05e00b6ac5940d0e3cd50491e3
  nodeSelector:
    node.kubernetes.io/type: general
  rankingWorker:
    enabled: true
  blockResetWorker:
    enabled: true
  walletMonitorWorker:
    enabled: true
