apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 9c-internal-mead
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/planetarium/9c-infra.git
    targetRevision: main
    path: 9c-internal-mead/chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: 9c-internal-mead
