apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argo-workflows-sso
  namespace: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: argocd-secretsmanager
    kind: SecretStore
  dataFrom:
  - extract:
      key: mothership-use2/argo-workflows/github-oauth-client
  target:
    name: argo-workflows-sso
    template:
      metadata:
        labels:
          app.kubernetes.io/instance: argo-workflows
          app.kubernetes.io/part-of: argo-workflows
    creationPolicy: Owner

