externalSecret:
  enabled: false

genesis:
  volume:
    storage: 100Mi

node:
  count: 1
  sequencerEnabled: false
  loadBalancerExternal: false
  opGeth:
    image: &op-geth-image us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101308.2
    port: &op-geth-port
      rpc: 8545
      wsrpc: 8546
      authrpc: 8551
      p2p: 30303
    volume: &op-geth-volume
      storage: 100Gi
  opNode:
    image: &op-node-image us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.7.0
    port: &op-node-port
      rpc: 8547
      p2p: 9003
      metrics: 7300
    volume: &op-node-volume
      storage: 100Mi

opBatcher:
  replicas: 1
  image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-batcher:v1.7.0
  port:
    rpc: 8548

opProposer:
  replicas: 1
  image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-proposer:v1.7.0
  port:
    rpc: 8560

blockscout:
  port: 5000
  loadBalancerExternal: false
  db:
    storage: 10Gi
