clusterName: 9c-internal
provider: RKE2

externalSecret:
  enabled: true
  provider: AWS
  prefix: "9c-internal-v2/external-services"

gateway:
  enabled: false
  services:
  - name: seasonpass-api-service
    hostnames:
    - seasonpass-internal.9c.gg
  - name: iap-backoffice
    hostnames:
    - iap-internal-backoffice.9c.gg

volumeReclaimPolicy: "Retain"

seasonpass:
  enabled: true
  image:
    tag: "git-092dcd7cc1b728e181c93e5b195787e7dc6f2746"

  api:
    enabled: true
    stage: "internal"

  worker:
    enabled: true
    serviceAccount:
      roleArn: "arn:aws:iam::319679068466:role/9c-internal-v2-seasonpass-worker"
    flower:
      enabled: true

  tracker:
    enabled: true

    resources:
      requests:
        cpu: 1
        memory: 4Gi

iap:
  backoffice:
    enabled: false
    image:
      tag: "git-9d98f43bbef5e5dadc3d30c26b7cdae482e01baf"
