clusterName: 9c-internal
provider: RKE2

externalSecret:
  enabled: true
  provider: AWS
  prefix: "9c-internal-v2/external-services"

gateway:
  services:
  - name: seasonpass-api-service
    hostnames:
    - seasonpass-internal.9c.gg
  - name: iap-backoffice
    hostnames:
    - iap-internal-backoffice.9c.gg

volumeReclaimPolicy: "Retain"

seasonpass:
  enabled: true
  image:
    tag: "git-1ee6503e60177e123da188d1fc2d67ed9edd3387"

  api:
    enabled: true
    stage: "internal"
    resources:
      limits:
        cpu: 0.5
        memory: 1Gi

  worker:
    enabled: true
    serviceAccount:
      roleArn: "arn:aws:iam::319679068466:role/9c-internal-v2-seasonpass-worker"
    flower:
      enabled: true
    resources:
      limits:
        cpu: 0.5
        memory: 1Gi

  tracker:
    enabled: true

    resources:
      limits:
        cpu: 0.5
        memory: 1Gi

iap:
  backoffice:
    enabled: false
    image:
      tag: "git-9d98f43bbef5e5dadc3d30c26b7cdae482e01baf"
