{{ if .Values.acc.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
  namespace: {{ $.Release.Name }}
  name: acc-redis
spec:
  serviceName: "acc-redis-service"
  replicas: 1
  selector:
    matchLabels:
      app: acc-redis
  template:
    metadata:
      labels:
        app: acc-redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: {{ $.Values.acc.redis.port }}
          name: redis
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: acc-env
        command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)"]
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
{{ end }}
