{{ if $.Values.blockIntervalNotifier.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: block-interval-notifier
  namespace: 9c-network
spec:
  schedule: "0 9 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: slack-notifier
            image: alpine
            command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache jq

              PROMETHEUS_RESPONSE=$(wget -qO- "${PROMETHEUS_URL}/api/v1/query?query=avg_over_time(ninechronicles_block_interval{group='validator'}[1d])")
              AVERAGE_VALUE=$(echo $PROMETHEUS_RESPONSE | jq -r '.data.result[-1].value[-1]')
              PAYLOAD="{\"text\":\"블록 인터벌 평균값은 '$AVERAGE_VALUE' 입니다.\"}"
              echo $PAYLOAD
              wget -qO- --post-data "$PAYLOAD" --header="Content-Type: application/json" $SLACK_WEBHOOK_URL > /dev/null 2>&1
            env:
            - name: PROMETHEUS_URL
              value: http://prometheus-server.monitoring.svc.cluster.local
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack
                  key: slack-webhook-url
          restartPolicy: OnFailure
{{ end }}
