{{ if $.Values.rudolfCurrencyNotifier.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rudolf-currency-notifier
  namespace: {{ $.Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
data:
  rudolf-currency-notifier.js: |- {{ tpl (.Files.Get "scripts/common/rudolf-currency-notifier.js") . | nindent 4 }}
{{ end }}