
apiVersion: v1
kind: ConfigMap
metadata:
  name: 9c-network-data-provider-script
  namespace: 9c-network
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
data:
  check_chain_tip.sh: |- {{ .Files.Get "scripts/data-provider/check_chain_tip.sh" | nindent 4 }}
