apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-download-snapshot-script
  namespace: {{ $.Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
data:
  download_snapshot.sh: |-
    #!/usr/bin/env bash

    cd /data

    apt-get -y update
    apt-get -y install jq wget aria2 sudo zip

    base_url=${1:-https://snapshots.nine-chronicles.com/main/partition}
    save_dir=${2:-"9c-main-snapshot_$(date +%Y%m%d_%H)"}
    download_option=$3
    service_name=$4
    SLACK_WEBHOOK=$5

    if [ $download_option = true ]
      aria2c "https://snapshots.nine-chronicles.com/main/partition/full/9c-main-snapshot.zip" -j10 -x10 --continue=true
      unzip -o "9c-main-snapshot.zip" -d "$save_dir"
    fi
