
apiVersion: v1
kind: ConfigMap
metadata:
  name: 9c-network-data-provider-script
  namespace: {{ $.Release.Name }} 
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
data:
  check_chain_tip.sh: |- {{ tpl (.Files.Get "scripts/data-provider/check_chain_tip.sh") . | nindent 4 }}
  {{- if eq $.Values.global.networkType "Internal" }}
  setup_internal_db.sh: |- {{ tpl (.Files.Get "scripts/data-provider/setup_internal_db.sh") . | nindent 4 }}
  {{- end }}
