{{- if eq $.Values.global.networkType "Main" }}
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        rewrite name 9c-main-tcp-seed-1.planetarium.dev tcp-seed-1.9c-network.svc.cluster.local
        rewrite name 9c-main-tcp-seed-2.planetarium.dev tcp-seed-2.9c-network.svc.cluster.local
        rewrite name 9c-main-tcp-seed-3.planetarium.dev tcp-seed-3.9c-network.svc.cluster.local
        rewrite name 9c-main-rpc-1.nine-chronicles.com remote-headless-1.9c-network.svc.cluster.local
        rewrite name 9c-main-rpc-2.nine-chronicles.com remote-headless-2.9c-network.svc.cluster.local
        rewrite name 9c-main-rpc-3.nine-chronicles.com remote-headless-3.9c-network.svc.cluster.local
        rewrite name 9c-main-rpc-4.nine-chronicles.com remote-headless-4.9c-network.svc.cluster.local
        rewrite name 9c-main-rpc-5.nine-chronicles.com remote-headless-5.9c-network.svc.cluster.local
        rewrite name 9c-main-validator-1.nine-chronicles.com validator-1.9c-network.svc.cluster.local
        rewrite name 9c-main-validator-2.nine-chronicles.com validator-2.9c-network.svc.cluster.local
        rewrite name 9c-main-validator-3.nine-chronicles.com validator-3.9c-network.svc.cluster.local
        rewrite name 9c-main-validator-4.nine-chronicles.com validator-4.9c-network.svc.cluster.local
        rewrite name 9c-main-test-1.nine-chronicles.com test-headless-1.9c-network.svc.cluster.local
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  labels:
    eks.amazonaws.com/component: coredns
    k8s-app: kube-dns
  name: coredns
  namespace: kube-system
{{- end }}
