{{- if $.Values.gateway.enabled }}
{{- range $service := $.Values.gateway.services }}
{{- range $route := $service.routes | default (list dict) }}
{{- $obj := merge $route $service }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: {{ $obj.kind | default "HTTPRoute" }}
metadata:
  name: gateway-{{ $obj.name }}-{{ $.Release.Name }}
  namespace: {{ $.Release.Name }}
spec:
  parentRefs:
  - name: traefik
    namespace: traefik
    sectionName: {{ $obj.sectionName | default "http" }}
  hostnames:
    {{- with ($service.hostnames | default (list $service.hostname)) }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  rules:
    - backendRefs:
      {{- range $ref := $obj.backendRefs | default (list dict) }}
      - name: {{ $ref.name | default $obj.name }}
        port: {{ $ref.port | default $obj.port | default "80" }}
      {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
