{{- if $.Values.gateway.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-{{ $.Release.Name }}
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $.Release.Name }}
  source:
    repoURL: https://github.com/traefik/traefik-helm-chart/
    path: traefik
    targetRevision: b8725498c2445da8ecc06f156ca69ddc1a56cce4
    helm:
      values: |
        image:
          tag: v3.2.0-rc2
        globalArguments:
          - --providers.kubernetesgateway.statusaddress.service.name=traefik-{{ $.Release.Name }}
          - --providers.kubernetesgateway.statusaddress.service.namespace={{ $.Release.Name }}
        ingressClass:
          enabled: false
        providers:
          kubernetesIngress:
            enabled: false
          kubernetesCRD:
            enabled: false
          kubernetesGateway:
            enabled: true
            experimentalChannel: true
            labelselector: app.kubernetes.io/instance=traefik-{{ $.Release.Name }}
        gatewayClass:
          name: traefik-{{ $.Release.Name }}
        service:
          annotations:
            {{- toYaml $.Values.global.service.annotations | nindent 12 }}
            {{- with $.Values.gateway.hostname }}
            external-dns.alpha.kubernetes.io/hostname: {{ . }}
            external-dns.alpha.kubernetes.io/ttl: '60'
            {{- end }}
        ports:
          websecure:
            targetPort: web
          {{- range $name, $config := $.Values.gateway.ports }}
          {{ $name }}:
            port: {{ $config.port }}
            protocol: {{ $config.portProtocol | default "TCP" }}
          {{- end }}
        gateway:
          listeners:
            web:
              port: 8000
              protocol: HTTP
            {{- range $name, $config := $.Values.gateway.ports }}
            {{ $name }}:
              port: {{ $config.port }}
              protocol: {{ $config.gatewayProtocol | default "HTTP" }}
            {{- end }}
---
{{- range $service := $.Values.gateway.services }}
{{- range $route := $service.routes | default (list dict) }}
{{- $obj := merge $route $service }}
---
apiVersion: gateway.networking.k8s.io/v1{{ if eq $obj.kind "TCPRoute" }}alpha2{{ end }}
kind: {{ $obj.kind | default "HTTPRoute" }}
metadata:
  name: gateway-{{ $obj.name }}
  namespace: {{ $.Release.Name }}
  annotations:
    {{- if eq $obj.kind "TCPRoute" }}
    {{- with $obj.hostname }}
    external-dns.alpha.kubernetes.io/hostname: {{ . }}
    external-dns.alpha.kubernetes.io/ttl: '60'
    {{- end }}
    {{- end }}
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: {{ $.Release.Name }}
    sectionName: {{ $obj.sectionName | default "web" }}
  {{- if not (eq $obj.kind "TCPRoute") }}
  hostnames:
    {{- with ($obj.hostnames | default (list $obj.hostname)) }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  rules:
    - backendRefs:
      {{- range $ref := $obj.backendRefs | default (list dict) }}
      - name: {{ $ref.name | default $obj.name }}
        port: {{ $ref.port | default $obj.port | default "80" }}
      {{- end }}
---
{{- end }}
{{- end }}
---
{{- end }}
