{{ if and .Values.marketService.enabled .Values.marketService.db.local }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: market-db
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: market-db
  namespace: {{ $.Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-db
  serviceName: market-db
  template:
    metadata:
      labels:
        app: market-db
    spec:
      containers:
        - env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                key: database
                name: market-db
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: market-db
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: user
                name: market-db
          image: postgres:13.3
          name: market-db
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: market-db-data
      {{- with $.Values.marketService.nodeSelector.read }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
  updateStrategy:
    type: RollingUpdate      
  volumeClaimTemplates:
    - metadata:
        name: market-db-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ $.Values.marketService.db.size }}
        storageClassName: {{ $.Release.Name }}-gp3
        volumeMode: Filesystem
{{ end }}
