{{ if and .Values.mimir.enabled .Values.mimir.diffWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mimir-diff-worker
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: mimir-diff-worker
  namespace: {{ $.Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir-diff-worker
  template:
    metadata:
      labels:
        app: mimir-diff-worker
    spec:
      containers:
        - name: mimir-diff-worker
          image: {{ $.Values.mimir.diffWorker.image.repository }}:{{ $.Values.mimir.diffWorker.image.tag }}
          env:
            - name: WORKER_Configuration__JwtSecretKey
              valueFrom:
                secretKeyRef:
                  name: mimir
                  key: JWT_SECRET_KEY
            - name: WORKER_Configuration__JwtIssuer
              valueFrom:
                secretKeyRef:
                  name: mimir
                  key: JWT_ISSUER
            - name: WORKER_Configuration__MongoDbConnectionString
              valueFrom:
                secretKeyRef:
                  name: mimir
                  key: MONGO_DB_CONNECTION_STRING
            - name: WORKER_Configuration__SentryDsn
              valueFrom:
                secretKeyRef:
                  name: mimir
                  key: SENTRY_DSN
            - name: WORKER_Logging__LogLevel__System.Net.Http.HttpClient
              value: "warning"
            - name: WORKER_Configuration__PollerType
              value: "DiffPoller"
            - name: WORKER_Configuration__EnableInitializing
              value: "true"
            - name: WORKER_Configuration__PlanetType
              value: "{{ $.Values.mimir.planetType }}"
            - name: WORKER_Configuration__HeadlessEndpoints__0
              valueFrom:
                secretKeyRef:
                  name: mimir
                  key: HeadlessEndpoints__0
            - name: WORKER_Configuration__HeadlessEndpoints__1
              valueFrom:
                secretKeyRef:
                  name: mimir
                  key: HeadlessEndpoints__1
          {{- with $.Values.mimir.diffWorker.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      restartPolicy: Always
      {{- with $.Values.mimir.diffWorker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  strategy:
    type: RollingUpdate
{{ end }}
