{{ if .Values.rudolfService.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.rudolfService.serviceAccount.roleArn }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: {{ $.Release.Name }}-9c-rudolf-iam-role
  namespace: {{ $.Release.Name }}

---


apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: 9c-rudolf
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: 9c-rudolf
  namespace: {{ $.Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 9c-rudolf
  template:
    metadata:
      labels:
        app: 9c-rudolf
    spec:
      containers:
        - name: 9c-rudolf
          env:
            - name: DATABASE_URL
              valueFrom: 
                secretKeyRef:
                  key: database-url
                  name: rudolf-service
            - name: GENESIS_BLOCK_HASH
              value: {{ quote .Values.rudolfService.config.genesisBlockHash }}
{{- if .Values.rudolfService.config.ncgMinter }}
            - name: NCG_MINTER
              value: {{ .Values.rudolfService.config.ncgMinter }}
{{- end }}
            - name: GQL_ENDPOINT
              value: {{ .Values.rudolfService.config.graphqlEndpoint }}
            - name: NC_GRAPHQL_ENDPOINT
              value: {{ .Values.rudolfService.config.graphqlEndpoint }}
            - name: AWS_KMS_KEY_ID
              value: {{ .Values.rudolfService.kms.keyId }}
            - name: AWS_KMS_PUBLIC_KEY
              value: {{ .Values.rudolfService.kms.publicKey }}
            - name: DEFAULT_START_NONCE
              value: {{ .Values.rudolfService.config.defaultNextNonce }}
          image: {{ $.Values.rudolfService.image.repository }}:{{ $.Values.rudolfService.image.tag }}
          ports:
            - containerPort: 3000
          resources:
            {{- toYaml $.Values.rudolfService.resources | nindent 12 }}
      {{- with $.Values.rudolfService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      serviceAccount: {{ $.Release.Name }}-9c-rudolf-iam-role
      serviceAccountName: {{ $.Release.Name }}-9c-rudolf-iam-role

---

{{ if .Values.rudolfService.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: rudolf-service
  namespace: {{ .Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    {{- with (deepCopy $.Values.global.service.annotations) }}
      {{ $_ := unset . "service.beta.kubernetes.io/aws-load-balancer-scheme" }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.rudolfService.service.public }}
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    {{- end }}
    {{- if .Values.rudolfService.service.securityGroupIds }}
    service.beta.kubernetes.io/aws-load-balancer-security-groups: {{ join "," .Values.rudolfService.service.securityGroupIds }}
    {{- end }}
    {{- with .Values.rudolfService.service.hostname }}
    external-dns.alpha.kubernetes.io/hostname: {{ . }}
    external-dns.alpha.kubernetes.io/ttl: '60'
    {{- end }}
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  - port: 443
    targetPort: 3000
    name: https
  selector:
    app: 9c-rudolf
{{ end }}

{{ end }}
