{{- if $.Values.backoffice.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ninechronicles-backoffice-env
  namespace: {{ $.Release.Name }}
type: Opaque
data:
  ASPNETCORE_ENVIRONMENT: {{ $.Values.backoffice.env.aspnetcoreEnvironment | b64enc }}
  NC_CLOUDFLARE_ACCESS_KEY_ID: {{ $.Values.backoffice.env.cloudflareAccessKeyId | b64enc }}
  NC_CLOUDFARE_SECRET_ACCESS_KEY: {{ $.Values.backoffice.env.cloudflareSecretAccessKey | b64enc }}
  NC_CLOUDFLARE_API_TOKEN: {{ $.Values.backoffice.env.cloudflareApiToken | b64enc }}
  NC_CLOUDFLARE_EMAIL: {{ $.Values.backoffice.env.cloudflareEmail | b64enc }}
  NC_CLOUDFLARE_ZONE_ID: {{ $.Values.backoffice.env.cloudflareZoneId | b64enc }}
  NC_CLOUDFLARE_BUCKET_NAME: {{ $.Values.backoffice.env.cloudflareBucketName | b64enc }}
  NC_CLOUDFLARE_ACCOUNT_ID: {{ $.Values.backoffice.env.cloudflareAccountId | b64enc }}
  NC_PRIVATE_KEY: {{ $.Values.backoffice.env.privateKey | b64enc }}
  NC_JWT_KEY: {{ $.Values.backoffice.env.jwtKey | b64enc }}
  NC_JWT_ISSUER: {{ $.Values.backoffice.env.jwtIssuer | b64enc }}
  NC_CDN_URL: {{ $.Values.backoffice.env.cdnUrl | b64enc }}
  NC_BLOCKHASH_ODIN: {{ $.Values.backoffice.env.blockHashOdin | b64enc }}
  NC_BLOCKHASH_HEIMDALL: {{ $.Values.backoffice.env.blockHashHeimdall | b64enc }}
  NC_BLOCKHASH_THOR: {{ $.Values.backoffice.env.blockHashThor | b64enc }}
  Authentication__Google__ClientId: {{ $.Values.backoffice.env.googleClientId | b64enc }}
  Authentication__Google__ClientSecret: {{ $.Values.backoffice.env.googleClientSecret | b64enc }}
{{- end }}