{{ if .Values.worldBoss.enabled }}
{{ if .Values.global.useExternalSecret }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: world-boss-env
  namespace: {{ $.Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ $.Release.Name }}-secretsmanager
    kind: SecretStore
  target:
    name: world-boss-env
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.clusterName }}/world-boss-env
{{ else }}
apiVersion: v1
kind: Secret
metadata:
  name: world-boss-env
  namespace: {{ $.Release.Name }}
stringData:
  celery-broker-url: {{ .Values.worldBoss.worldBossEnv.celeryBrokerUrl }}
  celery-result-backend: {{ .Values.worldBoss.worldBossEnv.celeryResultBackend }}
  database-url: {{ .Values.worldBoss.worldBossEnv.databaseUrl }}
  kms-key-id: {{ .Values.worldBoss.worldBossEnv.kmsKeyId }}
  redis-host: {{ .Values.worldBoss.worldBossEnv.redisHost }}
  redis-port: {{ .Values.worldBoss.worldBossEnv.redisPort }}
  slack-signing-secret: {{ .Values.worldBoss.worldBossEnv.slackSigningSecret }}
  slack-token": {{ .Values.worldBoss.worldBossEnv.slackToken }}
type: Opaque
{{ end }}
{{ end }}
