{{ if .Values.bridgeService.enabled }}
{{ if .Values.externalSecret.enabled }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: bridge-env
  namespace: {{ $.Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ $.Release.Name }}-secretsmanager
    kind: SecretStore
  target:
    name: bridge-env
    creationPolicy: Owner
  dataFrom:
  - extract:
      {{- if .Values.externalSecret.prefix }}
      key: {{ .Values.externalSecret.prefix }}/bridge-env
      {{- else }}
      key: {{ .Values.clusterName }}/bridge-env
      {{- end }}
{{ end }}
{{ end }}
