{{ if .Values.guildService.enabled }}
{{ if .Values.externalSecret.enabled }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: guild
  namespace: {{ $.Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ $.Release.Name }}-secretsmanager
    kind: SecretStore
  target:
    name: guild
    creationPolicy: Owner
  dataFrom:
  - extract:
      {{- if .Values.externalSecret.prefix }}
      key: {{ .Values.externalSecret.prefix }}/guild
      {{- else }}
      key: {{ .Values.clusterName }}/guild
      {{- end }}
{{ else }}
apiVersion: v1
kind: Secret
metadata:
  name: guild
  namespace: {{ $.Release.Name }}
stringData:
  connection-string: {{ .Values.guildService.db.connectionString }}
type: Opaque
{{ end }}
{{ end }}
