{{ if .Values.bridge.enabled }}
{{ if .Values.useExternalSecret }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: bridge
  namespace: {{ $.Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ $.Release.Name }}-secretsmanager
    kind: SecretStore
  target:
    name: bridge
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.clusterName }}/bridge
{{ else }}
apiVersion: v1
kind: Secret
metadata:
  name: bridge
  namespace: {{ $.Release.Name }}
stringData:
  9c-private-key: {{ .Values.bridge.bridgeEnv.privateKey }}
  mnemonic: {{ .Values.bridge.bridgeEnv.mnemonic }}
  slack-bridge-observer-token: {{ .Values.bridge.bridgeEnv.slackBridgeObserverToken }}
  slack-web-token: {{ .Values.bridge.bridgeEnv.slackWebToken }}
  etherscan-token: {{ .Values.bridge.bridgeEnv.etherscanToken }}
type: Opaque
{{ end }}
{{ end }}
