{{ if $.Values.snapshot.partition.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: snapshot-partition
  namespace: {{ $.Release.Name }}
spec:
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          {{- if $.Values.global.resetSnapshot }}
          - name: reset-snapshot
            {{- if and $.Values.remoteHeadless.image.repository $.Values.remoteHeadless.image.tag }}
            image: {{ $.Values.remoteHeadless.image.repository }}:{{ $.Values.remoteHeadless.image.tag }}
            {{- else }}
            image: {{ $.Values.global.image.repository }}:{{ $.Values.global.image.tag }}
            {{- end }}
            imagePullPolicy: Always
            command:
            - /bin/download_snapshot.sh
            args:
            - 'https://snapshots.nine-chronicles.com/{{ $.Values.snapshot.path }}'
            {{- if and (eq $.Values.provider "RKE2") (eq $.Release.Name "heimdall") }}
            - /output/headless
            {{- else }}
            - /data/headless
            {{- end }}
            - $(RESET_SNAPSHOT_OPTION)
            - snapshot
            - $(SLACK_WEBHOOK_URL)
            env:
            - name: RESET_SNAPSHOT_OPTION
              value: 'true'
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  key: slack-webhook-url
                  name: slack
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            resources: {}
            volumeMounts:
            - name: download-snapshot-script
              mountPath: /bin/download_snapshot.sh
              readOnly: true
              subPath: download_snapshot.sh
            - name: snapshot-volume-partition
            {{- if and (eq $.Values.provider "RKE2") (eq $.Release.Name "heimdall") }}
              mountPath: /output
            {{- else }}
              mountPath: /data
            {{- end }}
          {{- end }}

          - name: preload-headless
            {{- if and $.Values.remoteHeadless.image.repository $.Values.remoteHeadless.image.tag }}
            image: {{ $.Values.remoteHeadless.image.repository }}:{{ $.Values.remoteHeadless.image.tag }}
            {{- else }}
            image: {{ $.Values.global.image.repository }}:{{ $.Values.global.image.tag }}
            {{- end }}
            command:
            - /bin/preload_headless.sh
            args:
            - $(APP_PROTOCOL_VERSION_KEY)
            - $(SLACK_WEBHOOK_URL)
            {{- if and (eq $.Values.provider "RKE2") (eq $.Release.Name "heimdall") }}
            - /output/headless
            - /output/snapshot_logs
            {{- else }}
            - /data/headless
            - /data/snapshot_logs
            {{- end }}
            env:
            - name: APP_PROTOCOL_VERSION_KEY
              value: {{ $.Values.global.appProtocolVersion }}
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack
                  key: slack-webhook-url
            {{- with $.Values.snapshot.resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            volumeMounts:
            - name: script-volume
              mountPath: /bin/preload_headless.sh
              readOnly: true
              subPath: preload_headless.sh
            - name: snapshot-volume-partition
            {{- if and (eq $.Values.provider "RKE2") (eq $.Release.Name "heimdall") }}
              mountPath: /output
            {{- else }}
              mountPath: /data
            {{- end }}

          containers:
          - name: upload-snapshot
            image: {{ $.Values.snapshot.image }}
            command:
            - /bin/upload_snapshot.sh
            args:
            - $(APP_PROTOCOL_VERSION_KEY)
            - $(SLACK_WEBHOOK_URL)
            - $(CF_DISTRIBUTION_ID)
            {{- if $.Values.snapshot.uploadPath }}
            - {{ $.Values.snapshot.uploadPath }}
            {{- else }}
            - {{ $.Values.snapshot.path }}
            {{- end }}
            {{- if and (eq $.Values.provider "RKE2") (eq $.Release.Name "heimdall") }}
            - /output/snapshots
            - /output/headless
            {{- else }}
            - /data/snapshots
            - /data/headless
            {{- end }}

            env:
            - name: APP_PROTOCOL_VERSION_KEY
              value: {{ $.Values.global.appProtocolVersion }}
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack
                  key: slack-webhook-url
            - name: CF_DISTRIBUTION_ID
              valueFrom:
                secretKeyRef:
                  name: aws-keys
                  key: cf_distribution_id
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack
                  key: slack-token
            {{- with $.Values.snapshot.resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            volumeMounts:
            - name: script-volume
              mountPath: /bin/upload_snapshot.sh
              readOnly: true
              subPath: upload_snapshot.sh
            - name: download-snapshot-script
              mountPath: /bin/download_snapshot.sh
              readOnly: true
              subPath: download_snapshot.sh
            - name: aws-keys
              mountPath: /secret
              readOnly: true
            - name: snapshot-volume-partition
            {{- if and (eq $.Values.provider "RKE2") (eq $.Release.Name "heimdall") }}
              mountPath: /output
            {{- else }}
              mountPath: /data
            {{- end }}

          restartPolicy: OnFailure

          {{- with $.Values.snapshot.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          volumes:
          - name: script-volume
            configMap:
              defaultMode: 0700
              name: {{ .Release.Name }}-snapshot-script-partition
          - name: download-snapshot-script
            configMap:
              defaultMode: 0700
              name: {{ $.Release.Name }}-download-snapshot-script
          - name: aws-keys
            secret:
              secretName: aws-keys
          - name: snapshot-volume-partition
            {{- if and (eq $.Values.provider "RKE2") (eq $.Release.Name "heimdall") }}
            hostPath:
              path: /output
              type: Directory
            {{- else }}
            persistentVolumeClaim:
              claimName: snapshot-volume-partition
            {{- end }}


  schedule: 0 0 * * *
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  suspend: {{ $.Values.snapshot.partition.suspend }}
{{ end }}
