{{- if and (eq $.Values.provider "RKE2") $.Values.snapshot.partition.volume.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot-volume-partition
  namespace: {{ $.Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.snapshot.partition.volume.size }}
  volumeName: snapshot-volume-partition
  storageClassName: {{ $.Release.Name }}-longhorn
  volumeMode: Filesystem
{{- end }}
