{{- range .Values.global.storage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/filesystem-trim: enabled
  annotations:
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .data }}
  storageClassName: {{ $.Release.Name }}-longhorn
  volumeMode: Filesystem
---
{{- end }}
