{{- range .Values.global.storage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  namespace: odin
  labels:
    app: {{ .name }}
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .data }}
  storageClassName: {{ $.Release.Name }}-longhorn
  volumeMode: Filesystem
---
{{- end }}
