apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: test-headless-2
    app.kubernetes.io/instance: {{ $.Chart.Name }}
  name: test-headless-2
  namespace: {{ $.Chart.Name }}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: test-headless-2
  serviceName: test-headless-2
  template:
    metadata:
      labels:
        app: test-headless-2
      name: test-headless-2
    spec:
      containers:
      - args:
        - NineChronicles.Headless.Executable.dll
        - run
        - --app-protocol-version={{ $.Values.global.appProtocolVersion }}
        - --trusted-app-protocol-version-signer={{ $.Values.global.trustedAppProtocolVersionSigner }}
        - --genesis-block-path={{ $.Values.global.genesisBlockPath }}
        - --port={{ $.Values.testHeadless2.ports.headless }}
        - --no-miner
        - --store-type=rocksdb
        - --store-path=/data/headless
        {{- if $.Values.testHeadless2.useTurnServer }}
        {{- range $.Values.global.iceServers }}
        - --ice-server={{ . }}
        {{- end }}
        {{- else }}
        - --host={{ $.Values.testHeadless2.host }}
        {{- end }}
        {{- range $.Values.global.peerStrings }}
        - --peer={{ . }}
        {{- end }}
        - --graphql-server
        - --graphql-host=0.0.0.0
        - --graphql-port={{ $.Values.testHeadless2.ports.graphql }}
        - --rpc-server
        - --rpc-remote-server
        - --rpc-listen-host=0.0.0.0
        - --rpc-listen-port={{ $.Values.testHeadless2.ports.rpc }}
        - --no-cors
        - --chain-tip-stale-behavior-type=reboot
        - --sentry-dsn=https://625a444555a547e8822ee86d4f38f046@o195672.ingest.sentry.io/6197051
        - --sentry-trace-sample-rate=0.5
        - --tx-life-time=10
        - --network-type={{ $.Values.networkType }}
        {{- with $.Values.testHeadless2.extraArgs }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        command:
        - dotnet
        {{- if and $.Values.testHeadless2.image.repository $.Values.testHeadless2.image.tag }}
        image: {{ $.Values.testHeadless2.image.repository }}:{{ $.Values.testHeadless2.image.tag }}
        {{- else }}
        image: {{ $.Values.global.image.repository }}:{{ $.Values.global.image.tag }}
        {{- end }}
        imagePullPolicy: Always
        name: test-headless-2
        ports:
        - containerPort: {{ $.Values.testHeadless2.ports.graphql }}
          name: graphql
          protocol: TCP
        - containerPort: {{ $.Values.testHeadless2.ports.headless }}
          name: headless
          protocol: TCP
        - containerPort: {{ $.Values.testHeadless2.ports.rpc }}
          name: rpc
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /bin/liveness_probe.sh
          failureThreshold: 3
          initialDelaySeconds: 1800
          periodSeconds: 30
          timeoutSeconds: 30
        readinessProbe:
          exec:
            command:
            - /bin/readiness_probe.sh
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 10
        resources:
          {{- toYaml $.Values.testHeadless2.resources | nindent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: test-headless-data-2
        - mountPath: /bin/liveness_probe.sh
          name: probe-script
          readOnly: true
          subPath: liveness_probe.sh
        - mountPath: /bin/readiness_probe.sh
          name: probe-script
          readOnly: true
          subPath: readiness_probe.sh
        {{- if $.Values.testHeadless2.loggingEnabled }}
        - mountPath: /app/logs
          name: json-log
        {{- end }}
        {{- if $.Values.testHeadless2.loggingEnabled }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JSON_LOG_PATH
          value: ./logs/$(POD_NAME)_$(NAMESPACE_NAME)_test-headless-2.json
        {{- end }}
      nodeSelector:
        node.kubernetes.io/instance-type: m5.large
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 448
          name: {{ $.Chart.Name }}-probe-script
        name: probe-script
      - name: download-snapshot-script
        configMap:
          defaultMode: 0700
          name: {{ $.Chart.Name }}-download-snapshot-script
      {{- if $.Values.testHeadless2.loggingEnabled }}
      - hostPath:
          path: /var/log/headless
          type: DirectoryOrCreate
        name: json-log
      {{- end }}
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: test-headless-data-2
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ $.Values.testHeadless2.storage.data }}
      storageClassName: {{ $.Chart.Name }}-gp3
      volumeMode: Filesystem

