{{ range $.Values.network }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ . }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/planetarium/9c-infra.git
    targetRevision: main
    path: charts/all-in-one
    helm:
      valueFiles:
        {{- if eq .Values.clusterName "9c-main-apse1" }}
        - "../../9c-main/multiplanetary/network/general.yaml"
        {{- else }}
        - "../../{{ $.Values.path }}/network/general.yaml"
        {{- end }}
        - "../../{{ $.Values.path }}/network/{{ . }}.yaml"

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ . }}
---
{{ end }}
