apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
    app.kubernetes.io/instance: common-dbs
  name: mongodb-service
  namespace: common-dbs
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mongodb-ingressroute
  namespace: common-dbs
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "mongodb-internal.9c.gg"
    external-dns.alpha.kubernetes.io/ttl: '60'
spec:
  entryPoints:
    - mongodb
  routes:
    - match: HostSNI(`*`)
      services:
        - name: mongodb-service
          port: 27017
