apiVersion: v1
kind: Service
metadata:
  labels:
    app: psql
    app.kubernetes.io/instance: common-dbs
  name: psql-service
  namespace: common-dbs
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: psql
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: psql-ingressroute
  namespace: common-dbs
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "psql-internal.9c.gg"
    external-dns.alpha.kubernetes.io/ttl: '60'
spec:
  entryPoints:
    - postgresql
  routes:
    - match: HostSNI(`*`)
      services:
        - name: psql-service
          port: 5432
