apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: common-dbs
  name: redis-service
  namespace: common-dbs
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: redis-service
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: redis-ingressroute
  namespace: common-dbs
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "redis-internal.9c.gg"
    external-dns.alpha.kubernetes.io/ttl: '60'
spec:
  entryPoints:
    - redis
  routes:
    - match: HostSNI(`*`)
      services:
        - name: redis-service
          port: 6379

