apiVersion: v1
kind: Service
metadata:
  labels:
    app: rmq
    app.kubernetes.io/instance: common-dbs
  name: rmq-service
  namespace: common-dbs
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: amqp
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: management
      port: 15672
      protocol: TCP
      targetPort: 15672
  selector:
    app: rmq
  type: ClusterIP 
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: rmq-ingressroute
  namespace: common-dbs
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "rmq-internal.9c.gg"
    external-dns.alpha.kubernetes.io/ttl: '60'
spec:
  entryPoints:
    - amqp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: rmq-service
          port: 5672
