{{ range $idx := until (int .Values.count) }}
{{ $index := add $idx 1 }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: stateproxy-{{ $index }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: stateproxy-{{ $index }}
  namespace: {{ $.Release.Name }}
spec:
  podManagementPolicy: OrderedReady
  {{- if $.Values.replicas }}
  replicas: {{ $.Values.replicas }}
  {{- else }}
  replicas: 1
  {{- end }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: stateproxy-{{ $index }}
  serviceName: stateproxy-{{ $index }}
  template:
    metadata:
      labels:
        app: stateproxy-{{ $index }}
      name: stateproxy-{{ $index }}
    spec:
      initContainers:
        {{- if $.Values.global.resetSnapshot }}
        - args:
          - 'https://snapshots.nine-chronicles.com/{{ $.Values.snapshot.path }}'  
          - /data/headless
          - $(RESET_SNAPSHOT_OPTION)
          - stateproxy-{{ $index }}
          - $(SNAPSHOT_ROLLBACK_OPTION)
          command:
          - /bin/download_snapshot.sh
          env:
          - name: RESET_SNAPSHOT_OPTION  
            value: "{{ $.Values.global.resetSnapshot }}"
          - name: SNAPSHOT_ROLLBACK_OPTION
            value: "{{ $.Values.global.rollbackSnapshot }}"
          image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
          imagePullPolicy: Always
          name: reset-snapshot
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /bin/download_snapshot.sh
            name: download-snapshot-script
            readOnly: true
            subPath: download_snapshot.sh
          - mountPath: /data
            name: stateproxy-data-{{ $index }}
        {{- end }}
        - command:
          - sh
          - '-c'
          - >
            apk --no-cache add curl

            # Endpoint to check

            VALIDATOR="http://validator-5.{{ $.Release.Name }}.svc.cluster.local/ui/playground"

            echo Checking: ${VALIDATOR}

            while [[ $(curl --silent --output /dev/null --request GET
            --write-out "%{http_code}" ${VALIDATOR}) -ne 200 ]]; do
              echo "Not ready"
              sleep 5s
            done

            echo Ready
          image: alpine
          imagePullPolicy: Always
          name: wait
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      containers:
      - args:
        - NineChronicles.Headless.Executable.dll
        - run
        - --config={{ $.Values.global.AppsettingsPath }}
        {{- with $.Values.stateProxy.extraArgs }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        command:
        - dotnet
        image: {{ $.Values.stateProxy.image.repository }}:{{ $.Values.stateProxy.image.tag }}
        imagePullPolicy: Always
        name: stateproxy-{{ $index }}
        ports:
        - containerPort: {{ $.Values.stateProxy.ports.graphql }}
          name: graphql
          protocol: TCP
        - containerPort: {{ $.Values.stateProxy.ports.headless }}
          name: headless
          protocol: TCP
        - containerPort: {{ $.Values.stateProxy.ports.rpc }}
          name: rpc
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /bin/liveness_probe.sh
          failureThreshold: 5
          initialDelaySeconds: 1800
          periodSeconds: 60
          timeoutSeconds: 60
        readinessProbe:
          exec:
            command:
            - /bin/readiness_probe.sh
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 10
        resources:
          {{- toYaml $.Values.stateProxy.resources | nindent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: stateproxy-data-{{ $index }}
        - mountPath: /bin/liveness_probe.sh
          name: probe-script
          readOnly: true
          subPath: liveness_probe.sh
        - mountPath: /bin/readiness_probe.sh
          name: probe-script
          readOnly: true
          subPath: readiness_probe.sh
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        {{- with $.Values.stateProxy.env }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with $.Values.stateProxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.stateProxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 448
          name: {{ $.Release.Name }}-probe-script
        name: probe-script
      - name: download-snapshot-script
        configMap:
          defaultMode: 0700
          name: {{ $.Release.Name }}-download-snapshot-script
      {{- if and $.Values.stateProxy.storage.volumeNames (gt (len $.Values.stateProxy.storage.volumeNames) $idx) (ne (index $.Values.stateProxy.storage.volumeNames $idx) "") }}
      - name: stateproxy-data-{{ $index }}
        persistentVolumeClaim:
          claimName: {{ index $.Values.stateProxy.storage.volumeNames $idx }}
      {{- else }}
  volumeClaimTemplates:
  - metadata:
      name: stateproxy-data-{{ $index }}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ $.Values.stateProxy.storage.data }}
      storageClassName: {{ $.Release.Name }}-gp3
      volumeMode: Filesystem
      {{- end }}
  updateStrategy:
    type: RollingUpdate
---
{{ end }}
