apiVersion: v1
kind: Service
metadata:
  name: data-provider-write
  namespace: {{ $.Chart.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Chart.Name }}
spec:
  ports:
  - name: graphql
    port: 80
    targetPort: 80
  selector:
    app: data-provider-write
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: data-provider-read
  namespace: {{ $.Chart.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Chart.Name }}
spec:
  ports:
  - name: graphql
    port: 80
    targetPort: 80
  selector:
    app: data-provider-read
  type: LoadBalancer

