apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heimdall
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/planetarium/9c-infra.git
    targetRevision: main
    path: charts/all-in-one
    helm:
      valueFiles:
        - ../../9c-internal/heimdall/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: heimdall
