portalService:
  name: portal
  hostname: "nine-chronicles.com"
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000
  resources:
    limits:
      cpu: 4
      memory: 4Gi
    requests:
      cpu: 2
      memory: 3Gi
  image:
    repository: planetariumhq/9c-portal
    tag: "main-092dcd7cc1b728e181c93e5b195787e7dc6f2746"
    pullPolicy: Always
  externalSecret:
    enabled: true
    provider: AWS
    prefix: "9c-main/portal"
  env:
    NODE_ENV: production
    BASE_URL: "https://nine-chronicles.com"
    NEXT_PUBLIC_STATUS_SERVER_URL: "https://portal-status.nine-chronicles.com"
    S3_BANNER_BUCKET: "9c-portal-banner"
    BANNER_CLOUD_FRONT_DOMAIN: "https://d20llolvuaz1gj.cloudfront.net/"
    QA_ENABLED: false
    NEXT_PUBLIC_MAINNET_ENV: production
    NEXT_PUBLIC_PLANETARY_ENDPOINT: "https://planets.nine-chronicles.com/planets/"
backofficeService:
  name: backoffice
  hostname: "portal.planetarium.team"
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3001
  resources:
    limits:
      cpu: 4
      memory: 4Gi
    requests:
      cpu: 2
      memory: 3Gi
  image:
    repository: planetariumhq/9c-backoffice
    tag: "main-092dcd7cc1b728e181c93e5b195787e7dc6f2746"
    pullPolicy: Always
  externalSecret:
    enabled: true
    provider: AWS
    prefix: "9c-main/backoffice"
  env:
