portalService:
  name: portal
  hostnames:
    - "nine-chronicles.com"
    - "www.nine-chronicles.com"
  replicaCount: 2
  service:
    type: ClusterIP
    port: 3000
  resources:
    limits:
      cpu: 2
      memory: 3Gi
    requests:
      cpu: 2
      memory: 3Gi
  nodeSelector:
    node.kubernetes.io/type: baremetal
  image:
    repository: planetariumhq/9c-portal
    tag: main-70350306746768fc004b07cd971ff5660a771740
    pullPolicy: Always
  externalSecret:
    enabled: true
    provider: AWS
    prefix: "9c-main-v2/portal"
  env:
    NODE_ENV: production
    BASE_URL: "https://nine-chronicles.com"
    NEXT_PUBLIC_STATUS_SERVER_URL: "https://portal-status.nine-chronicles.com"
    S3_BANNER_BUCKET: "9c-portal-banner"
    BANNER_CLOUD_FRONT_DOMAIN: "https://d20llolvuaz1gj.cloudfront.net/"
    QA_ENABLED: false
    NEXT_PUBLIC_MAINNET_ENV: production
    NEXT_PUBLIC_PLANETARY_ENDPOINT: "https://planets.nine-chronicles.com/planets/"
backofficeService:
  name: backoffice
  hostname: "portal.planetarium.team"
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3001
  resources:
    limits:
      cpu: 2
      memory: 3Gi
    requests:
      cpu: 2
      memory: 3Gi
  nodeSelector:
    node.kubernetes.io/type: baremetal
  image:
    repository: planetariumhq/9c-portal-backoffice
    tag: main-56844b56ac698c61bd0d691dca44ecb8b6871b5d
    pullPolicy: Always
  externalSecret:
    enabled: true
    provider: AWS
    prefix: "9c-main-v2/backoffice"
  cronjobs:
    - name: withdrawal
      schedule: "*/2 * * * *"
      endpoint: "https://portal.planetarium.team/api/scheduler/withdrawal"
      tokenEnvName: "SCHEDULER_API_KEY"
    - name: withdrawal-status
      schedule: "*/15 * * * *"
      endpoint: "https://portal.planetarium.team/api/scheduler/transaction"
      tokenEnvName: "SCHEDULER_API_KEY"
