{{ if .Values.useExternalSecret }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: {{ $.Release.Name }}-slack
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ default "remote-headless" .Values.nameOverwrite }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ default "remote-headless" .Values.nameOverwrite }}-secretsmanager
    kind: SecretStore
  target:
    name: {{ $.Release.Name }}-slack
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.clusterName }}/slack
{{ else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-slack
  namespace: {{ $.Values.namespace }}
stringData:
  slack-token: {{ .Values.slackToken }}
  slack-webhook-url: {{ .Values.slackWebhookUrl }}
type: Opaque
{{ end }}
