---
{{ range $idx := until (int .Values.remoteHeadless.count) }}
{{ $index := add $idx 1 }}

apiVersion: v1
kind: Service
metadata:
  name: remote-headless-{{ $index }}
  namespace: {{ $.Chart.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Chart.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:319679068466:certificate/2481ac9e-2037-4331-9234-4b3f86d50ad3
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  externalTrafficPolicy: Local
  ports:
  - name: graphql
    port: {{ $.Values.remoteHeadless.ports.graphql }}
    targetPort: {{ $.Values.remoteHeadless.ports.graphql }}
  - name: rpc
    port: {{ $.Values.remoteHeadless.ports.rpc }}
    targetPort: {{ $.Values.remoteHeadless.ports.rpc }}
  - name: headless
    port: {{ $.Values.remoteHeadless.ports.headless }}
    targetPort: {{ $.Values.remoteHeadless.ports.headless }}
  - name: https
    port: 443
    targetPort: {{ $.Values.remoteHeadless.ports.graphql }}
  selector:
    app: remote-headless-{{ $index }}
  type: LoadBalancer

---
{{ end }}
---
