{{ if .Values.useExternalSecret }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: garage-signer-env
  namespace: {{ $.Chart.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Chart.Name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ $.Chart.Name }}-secretsmanager
    kind: SecretStore
  target:
    name: garage-signer-env
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.clusterName }}/garage-signer-env
{{ else }}
apiVersion: v1
kind: Secret
metadata:
  name: garage-signer-env
  namespace: {{ $.Chart.Name }}
stringData:
  celery-broker-url: {{ .Values.garageSignerEnv.celeryBrokerUrl }}
  celery-result-backend: {{ .Values.garageSignerEnv.celeryResultBackend }}
  database-url: {{ .Values.garageSignerEnv.databaseUrl }}
  kms-key-id: {{ .Values.garageSignerEnv.kmsKeyId }}
  redis-url: {{ .Values.garageSignerEnv.redisUrl }}
  database: ""
  db-user: ""
  db-password: ""
type: Opaque
{{ end }}
