{{ range $idx := until (int .Values.validator.count) }}
{{ $index := add $idx 1 }}
apiVersion: v1
kind: Service
metadata:
  name: validator-{{ $index }}
  namespace: {{ $.Chart.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Chart.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:319679068466:certificate/2481ac9e-2037-4331-9234-4b3f86d50ad3
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ports:
  - port: {{ $.Values.validator.ports.headless }}
    targetPort: {{ $.Values.validator.ports.headless }}
    name: headless
  - port: {{ $.Values.validator.ports.graphql }}
    targetPort: {{ $.Values.validator.ports.graphql }}
    name: gql
  - port: {{ $.Values.validator.ports.gossip }}
    targetPort: {{ $.Values.validator.ports.gossip }}
    name: gossip
  - port: 443
    targetPort: {{ $.Values.validator.ports.graphql }}
    name: https
    protocol: TCP
  selector:
    app: validator-{{ $index }}
  type: LoadBalancer

---
{{ end }}
