name: Release
on:
  workflow_dispatch:
    inputs:
      rc-number:
        required: true
        description: 'Rc number (e.g. 100310)'
      deploy-number:
        required: true
        description: 'Deploy number (e.g. 1)'

concurrency:
  group: release

jobs:
  extract-network:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    outputs:
      network: ${{ steps.extract.outputs.network }}
    steps:
      - uses: actions/checkout@v3
      - name: extract
        id: extract
        run: |
          if [[ ${{ github.head_ref }} =~ ^update-internal-manifests ]]; then
              echo "::set-output name=network::internal"
          elif [[ ${{ github.head_ref }} =~ ^update-main-manifests ]]; then
              echo "::set-output name=network::main"
          else
            echo "::set-output name=network::null"
          fi

  release:
    if: contains(github.head_ref, '-manifests-')
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.network }}
    steps:
      - uses: actions/checkout@v3
      - name: Release
        if: github.event.inputs.network != null
        uses: planetarium/9c-toolbelt@init
        with:
          COMMAND: update
          ENV: test
          GITHUB_TOKEN: ${{ secrets.P_GITHUB_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          KEY_PASSPHRASE: ${{ secrets.KEY_PASSPHRASE }}
          KEY_ADDRESS: ${{ secrets.KEY_ADDRESS }}
          KEY_PRIVATE: ${{ secrets.KEY_PRIVATE }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          network: ${{ github.event.inputs.network }}
