name: Reset bridge service

on:
  workflow_dispatch:
    inputs:
      network:
        required: true
        description: 'network type'
        default: 'internal'
        type: choice
        options:
        - heimdall-internal
        - thor-internal
        - heimdall-preview

jobs:
  reset-bridge-service:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.29.0'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Set namespace based on input
      run: |
        echo ${${{ github.event.inputs.network }}%"-internal"} >> $GITHUB_ENV

    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
      with:
        args: scale --replicas=0 statefulset/bridge-service -n ${{ env.NAMESPACE }}

    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
      with:
        args: scale --replicas=0 statefulset/bridge-service-db -n ${{ env.NAMESPACE }}

    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
      with:
        args: delete pvc/bridge-service-db-data-bridge-service-db-0 --namespace=${{ env.NAMESPACE }}

    - uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.10.13

    - run: |
        python -m pip install -r requirements.txt
        flit install
      name: install dependencies
      working-directory: ./scripts

    - name: Update 'bridgeService.rdb.defaultStartBlockIndex'
      run: |
        python cli.py update-bridge-service 9c-internal ${{ env.NAMESPACE }}
      working-directory: ./scripts
      env:
        GITHUB_TOKEN: ${{ secrets.P_GITHUB_TOKEN }}
