name: Internal Snapshot Reset
on:
  workflow_dispatch:

concurrency:
  group: release

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: internal
    steps:
      - uses: actions/checkout@v3
      - name: reset internal snapshot
        run: |
          echo "y" | bash .github/scripts/reset-snapshot.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
