name: Update values
on:
  workflow_dispatch:
    inputs:
      dir:
        required: true
        description: 'Dir'
        default: '9c-internal'
        type: choice
        options:
        - 9c-main
        - 9c-internal
        - 9c-sample
      headless:
        description: 'Source for headless to change (e.g. tag 1, branch release/3)'
      dataprovider:
        description: 'Same, for DP'
      seed:
        description: 'Same, for seed'
      world-boss-service:
        description: 'Same, for world-boss-service'
      market-service:
        description: 'Same, for market-service'
      bump-apv:
        required: true
        description: 'Bump APV'
        default: true
        type: boolean
      manual-args:
        description: 'Manual arguments e.g. "ninechronicles-dataprovider/from tag 1", delimiter is "|"'

jobs:
  update-values-file:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: make-args
        id: make-args
        run: |
          bash ./scripts/make-k8s-args.sh "${{ github.event.inputs.bump-apv }}" "${{ github.event.inputs.dir }}" "${{ github.event.inputs.headless }}" "${{ github.event.inputs.dataprovider }}" "${{ github.event.inputs.seed }}" "${{ github.event.inputs.world-boss-service }}" "${{ github.event.inputs.market-service }}" "${{ github.event.inputs.manual-args }}"

      - name: Update values
        uses: planetarium/9c-toolbelt@main
        with:
          COMMAND_LIST: "k8s|update-values|${{ steps.make-args.outputs.K8S_CMD_ARGS }}"
          ENV: production
          GITHUB_TOKEN: ${{ secrets.P_GITHUB_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
